-- 將可預約時間永久限制為台北時間07:00（含）至23:00（不含）。
update public.availability_rules set start_time=greatest(start_time,time '07:00'),end_time=least(end_time,time '23:00');
delete from public.availability_rules where end_time<=start_time;
delete from public.weekly_slot_overrides where start_time<time '07:00' or start_time>=time '23:00';
delete from public.slot_overrides where (slot_start at time zone 'Asia/Taipei')::time<time '07:00' or (slot_start at time zone 'Asia/Taipei')::time>=time '23:00';
alter table public.availability_rules drop constraint if exists availability_rules_booking_hours;
alter table public.availability_rules add constraint availability_rules_booking_hours check(start_time>=time '07:00' and end_time<=time '23:00');
alter table public.weekly_slot_overrides drop constraint if exists weekly_slot_overrides_booking_hours;
alter table public.weekly_slot_overrides add constraint weekly_slot_overrides_booking_hours check(start_time>=time '07:00' and start_time<time '23:00');
create or replace function public.get_available_slots(p_method_id uuid,p_days integer default 60) returns table(slot_start timestamptz,slot_end timestamptz) language sql security definer set search_path=public as $$
with dates as(select d::date local_date from generate_series((now() at time zone 'Asia/Taipei')::date,(now() at time zone 'Asia/Taipei')::date+least(greatest(p_days,1),180),interval '1 day')d),opened as(select gs slot_start,gs+interval '30 minutes' slot_end,d.local_date from dates d join availability_rules r on r.is_active and r.is_open and extract(isodow from d.local_date)=r.weekday and(r.valid_from is null or d.local_date>=r.valid_from)and(r.valid_until is null or d.local_date<=r.valid_until)cross join lateral generate_series((d.local_date+r.start_time)at time zone 'Asia/Taipei',((d.local_date+r.end_time)at time zone 'Asia/Taipei')-interval '30 minutes',interval '30 minutes')gs),weekly_forced as(select (d.local_date+w.start_time)at time zone 'Asia/Taipei' slot_start,((d.local_date+w.start_time)at time zone 'Asia/Taipei')+interval '30 minutes' slot_end,d.local_date from dates d join weekly_slot_overrides w on w.is_open and extract(isodow from d.local_date)=w.weekday),specific_forced as(select o.slot_start,o.slot_start+interval '30 minutes',((o.slot_start at time zone 'Asia/Taipei')::date)from slot_overrides o where o.consultation_method_id=p_method_id and o.is_open),combined as(select * from opened union select * from weekly_forced union select * from specific_forced)
select c.slot_start,c.slot_end from combined c where c.slot_start>now() and(c.slot_start at time zone 'Asia/Taipei')::time>=time '07:00' and(c.slot_start at time zone 'Asia/Taipei')::time<time '23:00' and not exists(select 1 from holidays h where h.holiday_date=c.local_date)and not exists(select 1 from weekly_slot_overrides w where not w.is_open and w.weekday=extract(isodow from c.local_date)and w.start_time=(c.slot_start at time zone 'Asia/Taipei')::time)and not exists(select 1 from availability_rules r where r.is_active and not r.is_open and r.weekday=extract(isodow from c.local_date)and(r.valid_from is null or c.local_date>=r.valid_from)and(r.valid_until is null or c.local_date<=r.valid_until)and(c.slot_start at time zone 'Asia/Taipei')::time>=r.start_time and(c.slot_start at time zone 'Asia/Taipei')::time<r.end_time and not exists(select 1 from weekly_slot_overrides w where w.is_open and w.weekday=r.weekday and w.start_time=(c.slot_start at time zone 'Asia/Taipei')::time))and not exists(select 1 from slot_overrides o where o.consultation_method_id=p_method_id and o.slot_start=c.slot_start and not o.is_open)and not exists(select 1 from bookings b where b.consultation_method_id=p_method_id and b.slot_start=c.slot_start and b.status<>'cancelled')order by c.slot_start;$$;
grant execute on function public.get_available_slots(uuid,integer) to anon;
