"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type ReturnItem = { index:number; itemTitle:string; content:string };
type Preview = { bookingNo:string; customerName:string; lineDisplayName:string; documentId:string; documentUrl:string; items:ReturnItem[] };
const normalizeDraft=(value:string)=>String(value||"").replace(/\r\n?/g,"\n").replace(/[ \t]+$/gm,"").replace(/\n[ \t]*\n(?:[ \t]*\n)+/g,"\n\n").trim();

export default function ConsultationReturnPage(){
  const [data,setData]=useState<Preview|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[active,setActive]=useState(0),[selected,setSelected]=useState<number[]>([]),[confirmOpen,setConfirmOpen]=useState(false),[editConfirm,setEditConfirm]=useState(false),[editing,setEditing]=useState(false),[drafts,setDrafts]=useState<Record<number,string>>({}),[sending,setSending]=useState(false),[sent,setSent]=useState(false);
  const editorRef=useRef<HTMLTextAreaElement|null>(null);
  useEffect(()=>{const params=new URLSearchParams(window.location.search),bookingNo=params.get("bookingNo")||"",documentId=params.get("documentId")||"";fetch(`/api/staff/consultation-return?bookingNo=${encodeURIComponent(bookingNo)}&documentId=${encodeURIComponent(documentId)}`).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"讀取失敗");setData(result);setSelected((result.items||[]).map((entry:ReturnItem)=>entry.index));setDrafts(Object.fromEntries((result.items||[]).map((entry:ReturnItem)=>[entry.index,entry.content])))}).catch(err=>setError(err instanceof Error?err.message:"讀取失敗")).finally(()=>setLoading(false))},[]);
  useEffect(()=>{if(editing)editorRef.current?.focus()},[editing]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){if(editConfirm)setEditConfirm(false);else if(confirmOpen&&!sending)setConfirmOpen(false);else if(editing)setEditing(false);else if(data?.documentUrl)window.location.href=data.documentUrl;return}if(confirmOpen||editConfirm||sending)return;if(event.key==="ArrowLeft"){event.preventDefault();setEditing(false);setActive(value=>Math.max(0,value-1))}if(event.key==="ArrowRight"){event.preventDefault();setEditing(false);setActive(value=>Math.min((data?.items.length||1)-1,value+1))}if(event.key==="Enter"&&!editing){event.preventDefault();const current=data?.items[active];if(current&&selected.includes(current.index))setEditConfirm(true)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[confirmOpen,editConfirm,sending,editing,data,active,selected]);
  const item=data?.items[active],selectedSet=useMemo(()=>new Set(selected),[selected]);
  const toggle=(index:number)=>setSelected(value=>value.includes(index)?value.filter(x=>x!==index):[...value,index].sort((a,b)=>a-b));
  async function send(){if(!data||sending)return;setSending(true);try{const editedItems=Object.fromEntries(data.items.filter(entry=>drafts[entry.index]!==entry.content).map(entry=>[entry.index,drafts[entry.index]]));const response=await fetch("/api/staff/consultation-return",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bookingNo:data.bookingNo,documentId:data.documentId,selectedIndexes:selected,editedItems})}),result=await response.json();if(!response.ok)throw new Error(result.error||"回傳失敗");setConfirmOpen(false);setSent(true)}catch(err){alert(err instanceof Error?err.message:"回傳失敗")}finally{setSending(false)}}
  if(loading)return <main className="returnResultPage"><div className="returnResultCard returnResultStatus">正在讀取 Google 諮詢單…</div></main>;
  if(error)return <main className="returnResultPage"><div className="returnResultCard returnResultStatus"><h1>無法開啟回傳頁面</h1><p>{error}</p><a href="/staff">回預約後台</a></div></main>;
  if(!data||!item)return null;
  const isSelected=selectedSet.has(item.index);
  return <main className="returnResultPage"><section className="returnResultCard">
    <header className="returnResultHeader"><div><span>回傳諮詢結果</span><div className="returnResultIdentity"><h1>{data.customerName}</h1><p>訂單編號：{data.bookingNo}</p></div></div><a className="returnResultEditLink" href={data.documentUrl}>返回 Google 文件編輯</a></header>
    {sent?<div className="returnResultSuccess"><div>✓</div><h2>諮詢結果已回傳 LINE</h2><p>已完成傳送。你可以回 Google 文件繼續編輯。</p><a href={data.documentUrl}>返回 Google 文件</a></div>:<><div className="returnResultSelect"><b>選擇要回傳的項目</b><div>{data.items.map(entry=><label key={entry.index} className={selectedSet.has(entry.index)?"selected":""}><input type="checkbox" checked={selectedSet.has(entry.index)} onChange={()=>toggle(entry.index)}/><span>{entry.index}</span><strong>{entry.itemTitle}</strong></label>)}</div></div>
      <div className="returnResultPager"><button disabled={active===0} onClick={()=>{setEditing(false);setActive(value=>Math.max(0,value-1))}}>‹</button><div><small>預覽 {active+1} / {data.items.length}</small><h2>項目 {item.index}｜{item.itemTitle}</h2></div><button disabled={active===data.items.length-1} onClick={()=>{setEditing(false);setActive(value=>Math.min(data.items.length-1,value+1))}}>›</button></div>
      {isSelected?<article className="returnResultPreview" tabIndex={0} onDoubleClick={()=>!editing&&setEditConfirm(true)}><div className="returnResultPreviewTitle"><span>LINE 將回傳以下內容</span><em>{editing?"編輯中，點框外完成":"按 Enter 可編輯"}</em></div>{editing?<textarea ref={editorRef} value={drafts[item.index]??item.content} onChange={event=>setDrafts(current=>({...current,[item.index]:event.target.value}))} onBlur={()=>{setDrafts(current=>({...current,[item.index]:normalizeDraft(current[item.index]??item.content)}));setEditing(false)}}/>:<pre>{drafts[item.index]??item.content}</pre>}</article>:<div className="returnResultPreviewEmpty">勾選這個項目後，才會顯示回傳內容預覽。</div>}
      <footer className="returnResultFooter"><a href={data.documentUrl}>返回編輯</a><button disabled={!selected.length} onClick={()=>setConfirmOpen(true)}>確認傳送（{selected.length} 項）</button></footer></>}
  </section>
  {editConfirm&&<div className="returnConfirmBackdrop" onClick={()=>setEditConfirm(false)}><div className="returnConfirmModal returnEditConfirm" onClick={event=>event.stopPropagation()}><span>編輯確認</span><h2>確定要編輯這項回傳內容？</h2><p>編輯後，LINE 將傳送你修改過的版本，不會改動原本的 Google 文件。</p><div className="returnConfirmActions"><button onClick={()=>setEditConfirm(false)}>取消</button><button onClick={()=>{setEditConfirm(false);setEditing(true)}}>開始編輯</button></div></div></div>}
  {confirmOpen&&<div className="returnConfirmBackdrop" onClick={()=>!sending&&setConfirmOpen(false)}><div className="returnConfirmModal" onClick={event=>event.stopPropagation()}><button className="returnConfirmClose" disabled={sending} onClick={()=>setConfirmOpen(false)}>×</button><span>最後確認</span><h2>確定回傳給 {data.customerName}？</h2><p>將把你勾選的 <b>{selected.length}</b> 個項目，以目前預覽的內容傳送到該 LINE 用戶。</p><div className="returnConfirmItems">{data.items.filter(entry=>selectedSet.has(entry.index)).map(entry=><div key={entry.index}><span>{entry.index}</span>{entry.itemTitle}</div>)}</div><div className="returnConfirmActions"><button disabled={sending} onClick={()=>setConfirmOpen(false)}>取消</button><button disabled={sending} onClick={send}>{sending?"傳送中…":"確定回傳 LINE"}</button></div></div></div>}
  </main>;
}
