const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {stripTypeScriptTypes}=require('node:module');const path=require('node:path');
const root=path.join(__dirname,'..');
function load(file){const context=vm.createContext({process,console,crypto:require('node:crypto')});vm.runInContext(stripTypeScriptTypes(fs.readFileSync(path.join(root,file),'utf8')).replace(/^import .*;\r?\n/gm,'').replace(/\bexport /g,''),context);return context;}
const text=load('lib/consultation-text.ts');
test('Q/A labels join content without swallowing next question or section',()=>{assert.equal(text.normalizeConsultationText('Q1:\n問題\nA1:\n\n內容是這樣\n\n第二段\nA2:\n\n【流年運勢】'),'Q1:問題\nA1:內容是這樣\n\n第二段\nA2:\n\n【流年運勢】');});
test('empty answers and existing paragraph breaks survive',()=>{assert.equal(text.normalizeConsultationText('Q1:問題\nA1:\n\nQ2:問題二\nA2:內容\n\n後續段落'),'Q1:問題\nA1:\n\nQ2:問題二\nA2:內容\n\n後續段落');});
test('structure guard detects swapped people, changed questions, and missing answer labels',()=>{for(const changed of ['【合盤】\n乙的個性\n甲本身個性\nQ1:問題\nA1:改文','【合盤】\n甲本身個性\n乙的個性\nQ1:新問題\nA1:改文','【合盤】\n甲本身個性\n乙的個性\nQ1:問題'])assert.notDeepEqual(text.consultationStructure('【合盤】\n甲本身個性\n乙的個性\nQ1:問題\nA1:原文'),text.consultationStructure(changed));});
const docs=load('lib/google-consultation-docs.ts');
test('health and overall templates share 15–35 and maximum age 99',()=>{const year=new Date().getFullYear();function body(code,age){return vm.runInContext(`documentBody({detail:{item_title:${JSON.stringify(code==='health'?'身體健康':'整體運勢')},booking_items:{code:${JSON.stringify(code)}},booking_consultation_answers:{profile_id:'p',consultation_profiles:{id:'p',name:'測試',birth_date:'${year-age+1}-01-01'},questions:[],extra_data:{}}}},1,1,'測試')`,docs).content;}for(const code of ['health','overall-fortune']){const content=body(code,15);assert.match(content,/15歲：/);assert.match(content,/35歲：/);assert.doesNotMatch(content,/36歲：/);const old=body(code,95);assert.match(old,/99歲：/);assert.doesNotMatch(old,/100歲：/);}});
test('consultation duration thresholds match scheduling formula',()=>{for(const [amount,minutes] of [[5700,30],[5701,35],[7900,35],[7901,40],[9100,45],[10300,50]])assert.equal(vm.runInContext(`videoConsultationMinutes(${amount})`,docs),minutes);});
