const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {stripTypeScriptTypes}=require('node:module');
function load(file,extra={}){const context=vm.createContext({process:{env:{OPENAI_API_KEY:'test-only'}},console,...extra});vm.runInContext(stripTypeScriptTypes(fs.readFileSync(file,'utf8')).replace(/^import .*;\r?\n/gm,'').replace(/\bexport /g,''),context);return context;}
const annual=load('lib/annual-fortune.ts');
test('15 years inclusive, age99 ceiling, invalid ages rejected',()=>{assert.deepEqual(Array.from(annual.annualAges(44)),Array.from({length:15},(_,i)=>i+44));assert.deepEqual(Array.from(annual.annualAges(98)),[98,99]);assert.equal(annual.annualAges(0).length,0);assert.equal(annual.annualAges(1.5).length,0)});
test('selected phrases only, age texts independent, manual text retained',()=>{const text=annual.composeAnnual(['wealth','exam'],0);assert.match(text,/財/);assert.match(text,/考試/);assert.doesNotMatch(text,/開刀|肝|小人|劫/);assert.notEqual(text,annual.composeAnnual(['wealth','exam'],1));const parsed=annual.parseAnnual('44歲：原本手寫\n45歲：另一年');assert.equal(parsed['44'].manual,true);assert.equal(annual.annualText([44,45],parsed),'44歲：原本手寫\n45歲：另一年');});
const time=load('lib/taipei-time.ts');const reminder=load('lib/staff-data-reminders.ts',{taipeiDateKey:time.taipeiDateKey,taipeiDateTimeInput:time.taipeiDateTimeInput});
test('Taiwan calendar four days and noon, independent of server timezone',()=>{const now=new Date('2026-10-01T04:00:00Z');assert.equal(reminder.isReminderNoon(now),true);assert.equal(reminder.isReminderNoon(new Date('2026-10-01T03:59:00Z')),false);assert.equal(reminder.reminderEligible({slot_start:'2026-10-05T23:50:00+08:00'},now),true);assert.equal(reminder.reminderEligible({slot_start:'2026-10-06T00:00:00+08:00'},now),false);for(const b of [{status:'cancelled'},{status:'expired'},{data_submitted_at:'2026-10-01'},{payment_status:'pending',expires_at:'2026-10-01T03:00:00Z'}])assert.equal(reminder.reminderEligible({slot_start:'2026-10-03T15:00:00+08:00',...b},now),false);assert.equal(reminder.reminderEligible({slot_start:now.toISOString()},now),false);assert.match(reminder.staffReminderText({slot_start:'2026-10-02T07:20:00Z',booking_no:'TEST',customers:{full_name:'測試'}},'https://example.com'),/15:20/);});
const q={slotIndex:3,questionNumber:1,question:'工作如何',profileName:'甲',source:'【整體建議】\n有貴人助力'};
function aiWith(choices){return load('lib/ai-question-choices.ts',{fetch:async()=>({ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({choices})}]}]})})});}
test('AI returns three candidates without writing answers',async()=>{const ai=aiWith([{slotIndex:3,options:['回答一','回答二','回答三']}]);const {choices:result}=await ai.generateQuestionChoices([q]);assert.equal(result.length,1);assert.equal(result[0].slotIndex,3);assert.equal(result[0].options.length,3);assert.equal(q.source,'【整體建議】\n有貴人助力');});
test('AI uses directional drafts for empty content and rejects malformed candidates',async()=>{const positive=aiWith([{slotIndex:3,options:['能順利進行','需要調整','目前受阻']}]);const generated=await positive.generateQuestionChoices([{...q,source:'【流年運勢】\n44歲：\n45歲：'}]);assert.equal(generated.choices[0].mode,'directions');assert.deepEqual(Array.from(generated.choices[0].labels),['正面','中性','負面']);for(const choices of [[{slotIndex:3,options:['一','二']}],[{slotIndex:4,options:['一','二','三']}],[]])await assert.rejects(aiWith(choices).generateQuestionChoices([q]));});
