const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {stripTypeScriptTypes}=require('node:module');
const route=stripTypeScriptTypes(fs.readFileSync('app/api/cron/staff-data-reminders/route.ts','utf8')).replace(/^import .*;\r?\n/gm,'').replace(/\bexport /g,'');
function fixture({enabled=true,profile='Nnn',completeOnRecheck=false,lineFail=false}={}){
 let pushes=0,inserts=0;const logs=new Map();const b={id:'b',booking_no:'TEST',slot_start:'2026-10-05T15:20:00+08:00',status:'pending_payment',payment_status:'pending',expires_at:'2026-10-02T00:00:00Z',customers:{full_name:'測試'}};
 const settings={enabled,recipient_line_user_id:'U_TEST',expected_full_name:'林啟恩',expected_line_name:'Nnn'};
 const db={from(table){let operation='read',payload,filteredId=false;const q={select(){return q},eq(key){if(key==='id'&&table==='bookings')filteredId=true;return q},is(){return q},gt(){return q},insert(v){operation='insert';payload=v;return q},update(v){operation='update';payload=v;return q},single(){return Promise.resolve(result())},then(ok,bad){return Promise.resolve(result()).then(ok,bad)}};function result(){if(table==='staff_data_reminder_settings')return{data:settings};if(table==='customers')return{data:[{full_name:'林啟恩',line_display_name:'Nnn',line_user_id:'U_TEST'}]};if(table==='bookings')return{data:filteredId?{...b,data_submitted_at:completeOnRecheck?'2026-10-01':null}:[b]};if(operation==='insert'){inserts++;if(logs.has('b'))return{error:{code:'23505'}};logs.set('b',payload);return{data:{id:'log'}}}return{data:null}}return q}};
 class FixedDate extends Date {constructor(...args){super(...(args.length?args:['2026-10-01T04:00:00Z']))}}
 const ctx=vm.createContext({Date:FixedDate,process:{env:{CRON_SECRET:'test',LINE_MESSAGING_CHANNEL_ACCESS_TOKEN:'test'}},NextResponse:{json:(body,options)=>({body,status:options?.status||200})},cookies:async()=>({get:()=>({value:'admin'})}),isAdminSession:()=>true,adminSupabase:()=>db,taipeiDateKey:()=> '2026-10-01',isReminderNoon:()=>true,reminderEligible:x=>!x.data_submitted_at,staffReminderText:()=> 'test message',fetch:async(url)=>{if(url.includes('/profile/'))return{ok:true,json:async()=>({displayName:profile})};pushes++;return{ok:!lineFail,status:500}}});vm.runInContext(route,ctx);
 return{get:async(dry=false,auth='Bearer test')=>ctx.GET({nextUrl:{origin:'https://example.com',searchParams:new URLSearchParams(dry?'dryRun=1':'')},headers:{get:()=>auth}}),counts:()=>({pushes,inserts})};
}
test('dry run previews without push or log insert',async()=>{const f=fixture();const r=await f.get(true);assert.equal(r.body.dryRun,true);assert.deepEqual(f.counts(),{pushes:0,inserts:0})});
test('concurrent cron requests claim once, second invocation never sends again',async()=>{const f=fixture();await Promise.all([f.get(),f.get()]);await f.get();assert.equal(f.counts().pushes,1)});
test('disabled setting, identity mismatch, and newly submitted data prevent sending',async()=>{for(const options of [{enabled:false},{profile:'其他人'},{completeOnRecheck:true}]){const f=fixture(options);await f.get();assert.equal(f.counts().pushes,0)}});
test('missing authorization cannot send; failed LINE delivery is recorded and not retried blindly',async()=>{const f=fixture({lineFail:true});assert.equal((await f.get(false,'')).status,401);assert.equal(f.counts().pushes,0);const r=await f.get();assert.equal(r.body.failed,1);await f.get();assert.equal(f.counts().pushes,1)});
