const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{stripTypeScriptTypes}=require('node:module');
const root=path.join(__dirname,'..');
function source(file){return stripTypeScriptTypes(fs.readFileSync(path.join(root,file),'utf8')).replace(/^import .*;\r?\n/gm,'').replace(/\bexport /g,'');}
function context(extra={}){const c=vm.createContext({process,console,Date,Intl,URLSearchParams,...extra});vm.runInContext(source('lib/taipei-time.ts'),c);return c;}
test('Taiwan wall time round-trip preserves 15:20 regardless of server timezone',()=>{const c=context();for(const input of ['2026-10-06T15:20','2026-10-06T15:20:00+08:00','2026-10-06T07:20:00Z']){assert.equal(c.parseTaipeiDateTime(input).toISOString(),'2026-10-06T07:20:00.000Z');assert.equal(c.taipeiDateTimeInput(input),'2026-10-06T15:20');}});
test('Taiwan midnight, month/year boundary and weekday are explicit',()=>{const c=context();assert.equal(c.taipeiDateKey('2026-09-30T15:59:59Z'),'2026-09-30');assert.equal(c.taipeiDateKey('2026-09-30T16:00:00Z'),'2026-10-01');assert.equal(c.taipeiYear(new Date('2026-12-31T16:00:00Z')),2027);assert.equal(c.calendarWeekday('2026-10-06'),2);assert.equal(c.taipeiDateTimeInput('2026-10-05T16:00:00Z'),'2026-10-06T00:00');});
async function patchFixture(input,{lines=false,fail=false,readFail=false}={}){
 let stored='2026-10-06T03:20:00Z',pushes=[];const booking={id:'b1',booking_no:'TEST',slot_start:stored,customers:{line_user_id:'mock-user'},consultation_methods:{code:'video',base_price:0},booking_details:[{item_id:'i1',quantity:1,booking_detail_sub_items:[]}]};
 const db={from(table){let action='select',columns='',value;const q={select(v){columns=v;return q;},update(v){action='update';value=v;return q;},insert(v){action='insert';value=v;return q;},delete(){action='delete';return q;},eq(){return q;},in(){return q;},single(){return q;},then(resolve,reject){let result={data:null,error:null};if(table==='bookings'&&action==='update'){if(fail)result.error={message:'slot conflict'};else if(value.slot_start)stored=value.slot_start;}else if(table==='bookings'&&columns==='slot_start'){result=readFail?{data:null,error:{message:'read failed'}}:{data:{slot_start:stored},error:null};}else if(table==='bookings')result.data=booking;else if(table==='booking_items')result.data=[{id:'i1',title:'身體健康',price:10300}];else if(table==='booking_details')result.data=action==='insert'?{id:'d1'}:[{item_title:'身體健康',quantity:1,booking_detail_sub_items:[]}];return Promise.resolve(result).then(resolve,reject);}};return q;}};
 const c=context({adminSupabase:()=>db,isAdminSession:()=>true,cookies:async()=>({get:()=>({value:'test'})}),NextResponse:{json:(body,options={})=>({body,status:options.status||200})},syncBookingCalendar:async()=>{},pushLineFlex:async(...args)=>pushes.push(args)});vm.runInContext(source('lib/line-message.ts'),c);c.pushLineFlex=async(...args)=>pushes.push(args);vm.runInContext(source('app/api/staff/bookings/route.ts'),c);
 const response=await c.PATCH({json:async()=>({bookingNo:'TEST',slotStart:input,...(lines?{lines:[{itemId:'i1',qty:1,subId:''}]}:{})}),nextUrl:{origin:'https://example.test'}});return {response,stored,pushes};
}
test('Actual booking PATCH stores Taiwan time and generates correct LINE Flex, with and without items',async()=>{for(const lines of [false,true])for(const input of ['2026-10-06T15:20','2026-10-06T15:20:00+08:00']){const {response,stored,pushes}=await patchFixture(input,{lines});assert.equal(response.status,200);assert.equal(stored,'2026-10-06T07:20:00.000Z');assert.equal(pushes.length,1);const texts=JSON.stringify(pushes[0][2]);assert.match(texts,/10月6日（.*二.*）/);assert.match(texts,/下午3:20/);assert.doesNotMatch(texts,/下午11:20/);}});
test('Failed booking save or missing persisted time sends no LINE notification',async()=>{for(const options of [{fail:true},{readFail:true}]){const {response,pushes}=await patchFixture('2026-10-06T15:20',options);assert.ok(response.status>=400);assert.equal(pushes.length,0);}});
