"use client";
import liff from "@line/liff";
import {useEffect,useMemo,useState} from "react";
type Method={id:string;code:"video"|"text";title:string;description:string|null;duration_minutes:number|null;base_price:number};type Sub={id:string;title:string;description:string|null;price:number;is_default:boolean};type Item={id:string;title:string;description:string|null;price:number;allow_quantity:boolean;option_mode:"none"|"single_required"|"multiple_optional";sub_items:Sub[]};type Slot={slot_start:string;slot_end:string};type Screen="method"|"slots"|"items"|"payment"|"done";
const money=(v:number)=>new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:0}).format(v);const dayKey=(v:string)=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Taipei"}).format(new Date(v));const dayLabel=(v:string)=>new Intl.DateTimeFormat("zh-TW",{month:"numeric",day:"numeric",weekday:"short",timeZone:"Asia/Taipei"}).format(new Date(v));const timeLabel=(v:string)=>new Intl.DateTimeFormat("zh-TW",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Taipei"}).format(new Date(v));
export default function Page(){
 const[auth,setAuth]=useState<"loading"|"ready"|"error">("loading"),[profile,setProfile]=useState<{displayName:string;pictureUrl?:string}|null>(null),[menu,setMenu]=useState(false),[screen,setScreen]=useState<Screen>("method"),[methods,setMethods]=useState<Method[]>([]),[items,setItems]=useState<Item[]>([]),[method,setMethod]=useState<Method|null>(null),[slots,setSlots]=useState<Slot[]>([]),[date,setDate]=useState(""),[slot,setSlot]=useState(""),[counts,setCounts]=useState<Record<string,number>>({}),[subs,setSubs]=useState<Record<string,boolean>>({}),[payment,setPayment]=useState<"credit_card"|"transfer"|"line_pay"|"">(""),[modal,setModal]=useState(false),[textOk,setTextOk]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[bookingNo,setBookingNo]=useState("");
 useEffect(()=>{(async()=>{try{const id=process.env.NEXT_PUBLIC_LIFF_ID;if(!id)throw new Error("尚未設定 LIFF ID");await liff.init({liffId:id});if(!liff.isLoggedIn()){liff.login({redirectUri:location.href});return}const token=liff.getAccessToken();const ar=await fetch("/api/line/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accessToken:token})}),aj=await ar.json();if(!ar.ok)throw new Error(aj.error);setProfile(aj);const r=await fetch("/api/catalog"),j=await r.json();if(!r.ok)throw new Error(j.error);setMethods(j.methods);setItems(j.items);setAuth("ready")}catch(e){setError(e instanceof Error?e.message:"載入失敗");setAuth("error")}})()},[]);
 const selected=items.filter(i=>(counts[i.id]||0)>0),total=(method?.base_price||0)+selected.reduce((a,i)=>a+i.price*counts[i.id]+i.sub_items.reduce((s,x)=>s+(subs[x.id]?x.price*counts[i.id]:0),0),0),dates=useMemo(()=>[...new Set(slots.map(x=>dayKey(x.slot_start)))],[slots]),daySlots=slots.filter(x=>dayKey(x.slot_start)===date),phase=screen==="items"?1:screen==="payment"||screen==="done"?2:0;
 function selectMethod(m:Method){setMethod(m);setTextOk(false);setSlot("");setDate("");setSlots([]);if(m.code==="text")setModal(true)}
 async function continueMethod(){if(!method)return setError("請選擇諮詢方式");setError("");if(method.code==="text"){if(!textOk)return setModal(true);setScreen("items");return}setBusy(true);try{const r=await fetch(`/api/slots?methodId=${method.id}`),j=await r.json();if(!r.ok)throw new Error(j.error);setSlots(j.slots);if(j.slots[0])setDate(dayKey(j.slots[0].slot_start));setScreen("slots")}catch(e){setError(e instanceof Error?e.message:"無法讀取時段")}finally{setBusy(false)}}
 function next(){setError("");if(screen==="slots"){if(!slot)return setError("請選擇日期與時段");setScreen("items")}else if(screen==="items"){if(!selected.length)return setError("請至少選擇一個諮詢項目");const missing=selected.find(i=>i.option_mode==="single_required"&&!i.sub_items.some(s=>subs[s.id]));if(missing)return setError(`「${missing.title}」請選擇一個方案`);setScreen("payment")}else if(screen==="payment"){if(!payment)return setError("請選擇付款方式");submit()}}
 async function submit(){setBusy(true);try{const r=await fetch("/api/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({methodId:method?.id,slotStart:slot||null,paymentMethod:payment,items:selected.map(i=>({item_id:i.id,quantity:counts[i.id],sub_item_ids:i.sub_items.filter(s=>subs[s.id]).map(s=>s.id)}))})}),j=await r.json();if(!r.ok)throw new Error(j.error);setBookingNo(j.booking.booking_no);setScreen("done")}catch(e){setError(e instanceof Error?e.message:"預約失敗")}finally{setBusy(false)}}
 if(auth!=="ready")return <main className="loginGate"><h1>林阿嫂線上諮詢預約</h1><p>{auth==="loading"?"正在確認 LINE 登入…":error}</p>{auth==="error"&&<button onClick={()=>location.reload()}>重新登入</button>}</main>;
 return <main className="shell"><section className="app"><header><div><h1>林阿嫂線上諮詢預約</h1></div><div className="account"><button onClick={()=>setMenu(!menu)}>{profile?.pictureUrl?<img src={profile.pictureUrl} alt="我的帳號"/>:<span>我</span>}</button>{menu&&<div className="accountMenu"><button onClick={()=>alert("我的預約功能即將開放")}>我的預約</button></div>}</div></header><nav>{["諮詢方式","諮詢項目","付款方式"].map((x,i)=><span key={x} className={phase===i?"active":phase>i?"done":""}>{x}</span>)}</nav><div className="content">{error&&<div className="error">{error}</div>}
 {screen==="method"&&<><div className="title"><h2>選擇諮詢方式</h2><p>請選擇文字諮詢或視訊諮詢</p></div><div className="methodCards">{methods.map(m=><button key={m.id} className={method?.id===m.id?"selected":""} onClick={()=>selectMethod(m)}><b>{m.title}</b><p>{m.description}</p>{m.code==="video"&&<strong>諮詢項目費用另加 {money(m.base_price)}</strong>}{m.code==="text"&&<small>約 7–30 天內收到諮詢結果</small>}</button>)}</div></>}
 {screen==="slots"&&<><div className="title"><h2>選擇視訊時間</h2><p>視訊諮詢每次 {method?.duration_minutes} 分鐘，另加 {money(method?.base_price||0)}</p></div>{dates.length===0?<div className="noSlots"><b>目前沒有可預約時段</b><p>請稍後再查看新的開放時間</p></div>:<div className="slotPicker"><section><h3>選擇日期</h3><div className="dates">{dates.map(d=><button key={d} className={date===d?"selected":""} onClick={()=>{setDate(d);setSlot("")}}>{dayLabel(`${d}T12:00:00+08:00`)}</button>)}</div></section><section><h3>選擇時段</h3><div className="times">{daySlots.length?daySlots.map(s=><button key={s.slot_start} className={slot===s.slot_start?"selected":""} onClick={()=>setSlot(s.slot_start)}>{timeLabel(s.slot_start)}</button>):<p>此日期沒有可預約時段</p>}</div></section></div>}</>}
 {screen==="items"&&<><div className="title"><h2>選擇諮詢項目</h2><p>文字與視訊使用相同的諮詢項目</p></div><div className="items">{items.map(i=><article key={i.id}><div className="itemMain"><div><b>{i.title}</b><p>{i.description}</p></div><strong>{money(i.price)}</strong></div><div className="counter"><button onClick={()=>setCounts(c=>({...c,[i.id]:Math.max(0,(c[i.id]||0)-1)}))}>−</button><span>{counts[i.id]||0}</span><button onClick={()=>setCounts(c=>({...c,[i.id]:i.allow_quantity?(c[i.id]||0)+1:1}))}>＋</button></div>{i.sub_items.length>0&&<div className="subs">{i.option_mode==="single_required"&&<p className="optionHint">請選擇一個方案</p>}{i.sub_items.map(s=><label key={s.id} className={(counts[i.id]||0)===0?"disabled":""}><input type={i.option_mode==="single_required"?"radio":"checkbox"} name={i.option_mode==="single_required"?`option-${i.id}`:undefined} disabled={(counts[i.id]||0)===0} checked={!!subs[s.id]} onChange={e=>setSubs(v=>{const n={...v};if(i.option_mode==="single_required")i.sub_items.forEach(x=>n[x.id]=false);n[s.id]=e.target.checked;return n})}/><span>{s.title}<small>{s.description}</small></span>{s.price>0&&<b>+{money(s.price)}</b>}</label>)}</div>}</article>)}</div><div className="total"><span>合計</span><b>{money(total)}</b></div></>}
 {screen==="payment"&&<><div className="title"><h2>選擇付款方式</h2><p>請選擇一種付款方式</p></div><div className="payments"><button className={payment==="credit_card"?"selected":""} onClick={()=>setPayment("credit_card")}><b>信用卡</b><span>›</span></button><button className={payment==="transfer"?"selected":""} onClick={()=>setPayment("transfer")}><b>銀行轉帳</b><span>›</span></button><button className={payment==="line_pay"?"selected":""} onClick={()=>setPayment("line_pay")}><b>LINE Pay</b><span>›</span></button></div><div className="summary"><p><span>諮詢方式</span><b>{method?.title}</b></p>{slot&&<p><span>預約時間</span><b>{dayLabel(slot)} {timeLabel(slot)}</b></p>}<p><span>付款金額</span><strong>{money(total)}</strong></p></div></>}
 {screen==="done"&&<div className="success"><div>✓</div><h2>預約已送出</h2><p>預約編號</p><strong>{bookingNo}</strong><p>後續訊息將透過 LINE 傳送。</p></div>}</div>{screen!=="done"&&<footer>{screen!=="method"&&<button className="back" onClick={()=>setScreen(screen==="slots"?"method":screen==="items"?(method?.code==="video"?"slots":"method"):"items")}>上一步</button>}<button className="next" disabled={busy||screen==="slots"&&dates.length===0} onClick={screen==="method"?continueMethod:next}>{busy?"處理中…":screen==="payment"?"確認預約":"下一步"}</button></footer>}
 {modal&&<div className="modalBackdrop"><div className="modal"><h2>文字諮詢說明</h2><ul><li>約 7–30 天內收到諮詢結果。</li><li>確認資料時，每項預約可提出 3 個問題。</li><li>收到結果後 8 小時內，每項預約可提出 2 個補充問題。</li></ul><button onClick={()=>{setTextOk(true);setModal(false)}}>我已了解</button></div></div>}</section></main>}
