"use client";
import { useEffect, useRef, useState } from "react";
import { lunarProfile } from "@/lib/lunar-profile";
const times=["子時（23:00–01:00）","丑時（01:00–03:00）","寅時（03:00–05:00）","卯時（05:00–07:00）","辰時（07:00–09:00）","巳時（09:00–11:00）","午時（11:00–13:00）","未時（13:00–15:00）","申時（15:00–17:00）","酉時（17:00–19:00）","戌時（19:00–21:00）","亥時（21:00–23:00）","不確定"];
const empty={profile_type:"person",relationship:"本人",relationship_detail:"",name:"",gender:"",birth_date:"",lunar_birth_text:"",zodiac:"",birth_shichen:"",address:"",death_date:"",lunar_death_text:"",death_shichen:"",owner_profile_id:"",photo_data:"",notes:""};
const lunar=(v:string)=>lunarProfile(v).lunar_birth_text;
const zodiac=(v:string)=>{const a=["猴","雞","狗","豬","鼠","牛","虎","兔","龍","蛇","馬","羊"];return v?a[new Date(`${v}T12:00:00`).getFullYear()%12]:""};
export default function BookingData(){
 const savingRef=useRef(0);
 const [order,setOrder]=useState(""),[data,setData]=useState<any>(null),[form,setForm]=useState<any>(empty),[showForm,setShowForm]=useState(false),[editingId,setEditingId]=useState(""),[deleteConfirmId,setDeleteConfirmId]=useState(""),[petFields,setPetFields]=useState(false),[msg,setMsg]=useState(""),[saving,setSaving]=useState(false),[savingItems,setSavingItems]=useState(0),[submitWaiting,setSubmitWaiting]=useState(false),[confirmSubmit,setConfirmSubmit]=useState(false),[missingItems,setMissingItems]=useState<string[]>([]);
 async function load(o=order){const r=await fetch(`/api/booking-data?order=${encodeURIComponent(o)}`),j=await r.json();if(r.ok)setData(j);else setMsg(j.error)}
 useEffect(()=>{const o=new URLSearchParams(location.search).get("order")||"";setOrder(o);void load(o)},[]);
 function date(field:"birth_date"|"death_date",v:string){setForm({...form,[field]:v,[field==="birth_date"?"lunar_birth_text":"lunar_death_text"]:lunar(v),...(field==="birth_date"?{zodiac:zodiac(v)}:{})})}
 function photo(file?:File){if(!file)return;const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{const max=1000,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d")!.drawImage(image,0,0,canvas.width,canvas.height);setForm((value:any)=>({...value,photo_data:canvas.toDataURL("image/jpeg",.72)}));URL.revokeObjectURL(url)};image.src=url}
 async function add(){setSaving(true);const payload=editingId?{order,action:"update_profile",profileId:editingId,profile:form}:{order,profile:form},r=await fetch("/api/booking-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),j=await r.json();setSaving(false);if(!r.ok)return setMsg(j.error);setForm(empty);setEditingId("");setShowForm(false);setMsg("資料已儲存，下次可直接選取");void load()}
 async function removeProfile(id:string){const r=await fetch("/api/booking-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({order,action:"delete_profile",profileId:id})}),j=await r.json();setDeleteConfirmId("");if(r.ok){setShowForm(false);setEditingId("");setMsg("資料已刪除");void load()}else setMsg(j.error)}
 async function assign(detailId:string,profileId:string,questions:string[],profileIds?:string[],extraData?:any){savingRef.current++;setSavingItems(savingRef.current);try{const r=await fetch("/api/booking-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({order,detailId,profileId,profileIds,questions,extraData})}),j=await r.json();setMsg(r.ok?"此項目的問事資料已儲存":j.error);if(r.ok)await load();return r.ok}finally{savingRef.current=Math.max(0,savingRef.current-1);setSavingItems(savingRef.current)}}
 async function submitAll(){setSubmitWaiting(true);while(savingRef.current>0)await new Promise(resolve=>setTimeout(resolve,400));setSubmitWaiting(false);setSaving(true);const r=await fetch("/api/booking-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({order,action:"submit"})}),j=await r.json();setSaving(false);if(!r.ok)return setMsg(j.error);setConfirmSubmit(false);location.assign(process.env.NEXT_PUBLIC_LINE_OFFICIAL_ACCOUNT_URL||`/my-bookings?order=${encodeURIComponent(order)}`)}
 const profiles=data?.profiles||[],uniqueProfiles=profiles.filter((p:any,i:number,all:any[])=>all.findIndex((x:any)=>x.profile_type===p.profile_type&&x.relationship===p.relationship&&x.name===p.name)===i),details=data?.booking?.booking_details||[];
 return <main className="dataPage questionPage"><header><button onClick={()=>location.href="/"}>‹</button><div><h1>提供問事資料</h1><p>訂單編號：{order}</p></div></header>{msg&&<div className="questionMessage">{msg}</div>}
 <section className="profilePicker"><div className="sectionHead"><div><h2>諮詢者資料</h2><p>儲存一次，下次預約即可快速選取。</p></div><button onClick={()=>{setEditingId("");setForm(empty);setShowForm(true)}}>＋ 新增資料</button></div>{!data&&<p className="profilesLoading">載入中，請稍後10～20秒…</p>}<div className="savedProfiles">{uniqueProfiles.map((p:any)=><article role="button" tabIndex={0} onClick={()=>{setEditingId(p.id);setForm({...empty,...p});setPetFields(p.profile_type==="pet");setShowForm(true)}} key={p.id}>{p.profile_type==="pet"&&(p.photo_data?<img src={p.photo_data} alt=""/>:<span>寵</span>)}<div><b>{p.name}</b><small>{p.relationship}{p.relationship_detail?`・${p.relationship_detail}`:""}</small></div></article>)}</div></section>
 {showForm&&<div className="modalBackdrop"><div className="modal profileModal"><button className="closeProfile" onClick={()=>setShowForm(false)}>×</button><h2>{editingId?"編輯諮詢者資料":"新增可快速選取的資料"}</h2><div className="profileKinds"><button className={form.profile_type==="person"?"selected":""} onClick={()=>{setPetFields(false);setForm({...empty,profile_type:"person",relationship:"親友"})}}>親友</button><button className={form.profile_type==="deceased"?"selected":""} onClick={()=>{setPetFields(false);setForm({...empty,profile_type:"deceased",relationship:"過世親人"})}}>過世親友</button><button className={form.profile_type==="pet"?"selected":""} onClick={()=>{setPetFields(false);setForm({...empty,profile_type:"pet",relationship:"往生寵物"})}}>往生寵物</button></div><div className="profileFields">
 {form.profile_type==="pet"&&<label className="wide">先選取寵物主人<select value={form.owner_profile_id} onChange={e=>setForm({...form,owner_profile_id:e.target.value})}><option value="">請選擇主人</option>{uniqueProfiles.filter((p:any)=>p.profile_type==="person").map((p:any)=><option key={p.id} value={p.id}>{p.name}（{p.relationship_detail||p.relationship}）</option>)}</select></label>}
 {form.profile_type==="pet"&&!petFields&&<button className="wide addPetFields" disabled={!form.owner_profile_id} onClick={()=>setPetFields(true)}>＋ 新增往生寵物資料</button>}
 {(form.profile_type!=="pet"||petFields)&&<><label>{form.profile_type==="pet"?"寵物姓名":"姓名"}<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>{form.profile_type!=="pet"&&<label>他是我的…<input placeholder="例如：母親、朋友" value={form.relationship_detail} onChange={e=>setForm({...form,relationship_detail:e.target.value})}/></label>}{form.profile_type==="pet"&&<><label className="wide">出生日期<input type="date" value={form.birth_date} onChange={e=>date("birth_date",e.target.value)}/></label><label className="wide readonly">農曆生日<input readOnly value={form.lunar_birth_text}/></label><label className="wide">寵物照片<small>請上傳光線充足、主體清晰且完整呈現寵物樣貌的照片。</small><input type="file" accept="image/*" onChange={e=>photo(e.target.files?.[0])}/></label></>}</>}
 {(form.profile_type!=="pet"||petFields)&&<>{form.profile_type!=="pet"&&<><label>性別<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">請選擇</option><option>男</option><option>女</option><option>其他</option></select></label><label className="wide">國曆生日<input type="date" value={form.birth_date} onChange={e=>date("birth_date",e.target.value)}/></label><label className="wide readonly">農曆生日<input readOnly value={form.lunar_birth_text}/></label><label className="readonly">生肖<input readOnly value={form.zodiac}/></label><label>出生時辰<select value={form.birth_shichen} onChange={e=>setForm({...form,birth_shichen:e.target.value})}><option value="">請選擇</option>{times.map(x=><option key={x}>{x}</option>)}</select></label></>}
 {form.profile_type==="person"&&<label className="wide">完整地址<small><input type="checkbox" onChange={e=>e.target.checked&&setForm({...form,address:data?.customer?.full_address||""})}/> 同我的地址</small><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label>}
 {form.profile_type!=="person"&&<><label className="wide">{form.profile_type==="pet"?"寵物資料":"生前住址"}{form.profile_type==="pet"?null:<><small><input type="checkbox" onChange={e=>e.target.checked&&setForm({...form,address:data?.customer?.full_address||""})}/> 同我的地址</small><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></>}</label><label className="wide">國曆往生日期<input type="date" value={form.death_date} onChange={e=>date("death_date",e.target.value)}/></label><label className="wide readonly">農曆往生日期<input readOnly value={form.lunar_death_text}/></label><label>往生時辰<select value={form.death_shichen} onChange={e=>setForm({...form,death_shichen:e.target.value})}><option value="">請選擇</option>{times.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">備註<textarea placeholder="例如：只記得大約年份" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></>}</>}
 </div><div className="profileEditActions"><button className="saveProfile" disabled={!form.name||saving} onClick={()=>void add()}>{saving?"儲存中…":"儲存"}</button>{editingId&&form.relationship!=="本人"&&<button className="deleteProfile" onClick={()=>setDeleteConfirmId(editingId)}>刪除該資料</button>}</div></div></div>}{deleteConfirmId&&<div className="modalBackdrop deleteConfirm"><div className="modal"><h2>確認刪除資料</h2><p>該筆資料刪除後將無法復原，請確認是否要刪除。</p><button onClick={()=>void removeProfile(deleteConfirmId)}>確認刪除</button><button className="cancel" onClick={()=>setDeleteConfirmId("")}>取消</button></div></div>}
 <div className="answerSection"><h2>逐項指定問事資料</h2><p>每個項目最多可填三個具體問題；沒有問題可以留白。</p>{details.map((d:any)=>{const old=data?.links?.find((x:any)=>x.booking_detail_id===d.id);return <Answer key={d.id} detail={d} profiles={uniqueProfiles} initialProfile={old?.profile_id||""} initialProfiles={old?.booking_answer_participants?.sort((a:any,b:any)=>a.position-b.position).map((a:any)=>a.profile_id)||[]} initialQuestions={old?.questions||[]} locked={Boolean(data?.booking?.data_submitted_at)} save={assign}/>})}</div>{(savingItems>0||submitWaiting)&&<p className="savingNotice">資料儲存中，請稍後5～10秒…</p>}{!data?.booking?.data_submitted_at?<button className="submitAllData" onClick={()=>{const missing=details.filter((d:any)=>!data?.links?.some((x:any)=>x.booking_detail_id===d.id)).map((d:any)=>d.item_title);if(missing.length){setMissingItems(missing);return}setConfirmSubmit(true)}}>確認無誤，送出資料</button>:<div className="submittedNotice">資料已送出，如需修改請透過 LINE 聯絡助理。</div>}{missingItems.length>0&&<div className="modalBackdrop"><div className="modal missingItemsModal"><h2>還有項目尚未儲存</h2><p>請先完成下列項目：</p><ul>{missingItems.map((name,i)=><li key={i}>{name}</li>)}</ul><button onClick={()=>setMissingItems([])}>我知道了</button></div></div>}{confirmSubmit&&<div className="modalBackdrop"><div className="modal submitConfirm"><h2>送出前請再次確認</h2><p>請再仔細確認所有資料是否正確。送出後將無法自行修改；若需要調整，請透過 LINE 傳訊息聯絡助理，我們會協助您處理。</p>{(savingItems>0||submitWaiting)&&<p className="savingNotice">資料儲存中，請稍後5～10秒…</p>}<button onClick={()=>void submitAll()} disabled={saving}>{saving?"送出中…":"確認無誤，正式送出"}</button><button className="cancel" onClick={()=>setConfirmSubmit(false)}>返回檢查</button></div></div>}</main>
}
function Answer({detail,profiles,initialProfile,initialProfiles,initialQuestions,save,locked}:any){
 const initialQuestionCount=Math.max(1,Math.min(3,initialQuestions.findLastIndex?.((q:string)=>Boolean(q))+1||1));
 const [profileId,setProfileId]=useState(initialProfile),[profileIds,setProfileIds]=useState<string[]>(initialProfiles.filter((id:string)=>id!==initialProfile)),[questions,setQuestions]=useState<string[]>(Array.from({length:initialQuestionCount},(_,i)=>initialQuestions[i]||"")),[questionLimit,setQuestionLimit]=useState(false),[extra,setExtra]=useState<any>(detail.answer_extra_data||{}),[targetQuestions,setTargetQuestions]=useState<Record<string,string[]>>(detail.answer_extra_data?.target_questions||{}),[saved,setSaved]=useState(Boolean(initialProfile)),[open,setOpen]=useState(!initialProfile);
 const code=detail.booking_items?.code||"",kind=code==="deceased-relative"?"deceased":code.includes("pet")?"pet":"person",allowed=profiles.filter((p:any)=>p.profile_type===kind),sub=detail.booking_detail_sub_items?.map((s:any)=>s.sub_item_title).join("、")||"",title=detail.item_title||"",relation=code==="past-life-relationship"||title.includes("與他人前世關係"),marriage=code==="marriage-bazi"||title.includes("合婚")||title.includes("合八字")||title.includes("感情運勢與關係合盤")||title.includes("關係合盤"),company=code==="rename-company"&&(sub.includes("公司命名")||sub.includes("公司改名")),datePick=code==="date-time-selection",count=relation?(hasCount(sub,3)?3:hasCount(sub,2)?2:1):marriage?(hasCount(sub,3)||sub.includes("增加2人")||sub.includes("加看兩位")?3:hasCount(sub,2)||sub.includes("增加1人")||sub.includes("加看一位")?2:1):1,ids=Array.from({length:count},(_,i)=>profileIds[i]||""),self=profiles.find((p:any)=>p.relationship==="本人"),primaryId=profileId||self?.id||"",hasDuplicate=[primaryId,...ids].filter(Boolean).some((id,i,all)=>all.indexOf(id)!==i);
 const newbornNaming=code==="naming"&&(sub.includes("新生兒")||title.includes("新生兒")),home=code==="home-energy"||title.includes("陽宅"),lawsuit=code==="lawsuit-benefactor"||title.includes("官司"),personOptions=profiles.filter((p:any)=>p.profile_type==="person"),personSelect=(value:string,key:string,label:string)=><label>{label}<select disabled={locked} value={value||""} onChange={e=>change(key,e.target.value)}><option value="">請選擇資料</option>{personOptions.map((p:any)=><option key={p.id} value={p.id}>{p.name}（{p.relationship_detail||p.relationship}）</option>)}</select></label>;
 useEffect(()=>{setProfileIds(previous=>Array.from({length:count},(_,index)=>previous[index]||""))},[count]);
 const change=(key:string,value:any)=>{setExtra({...extra,[key]:value});setSaved(false)},chooser=(id:string,i:number)=><select disabled={locked} value={id||""} onChange={e=>{const n=[...ids];n[i]=e.target.value;setProfileIds(n);setSaved(false)}}><option value="">請選擇資料</option>{profiles.filter((p:any)=>p.profile_type==="person").map((p:any)=><option key={p.id} value={p.id} disabled={p.id!==id&&[primaryId,...ids].includes(p.id)}>{p.name}（{p.relationship_detail||p.relationship}）</option>)}</select>;
 if(saved&&!open)return <article className="answerCard collapsed"><div className="answerTitle"><span>{detail.item_title}</span><small>{sub}</small></div><button aria-label={locked?"查看":"點此編輯"} title={locked?"查看":"點此編輯"} onClick={()=>setOpen(true)}>{locked?"查看":"✓"}</button></article>;
 return <article className="answerCard"><div className="answerTitle"><span>{detail.item_title}</span><small>{sub}</small></div>
 {relation||marriage?<div className="relationChooser" key={`${detail.id}-${count}`}><label>這個項目是為誰諮詢？<select disabled={locked} value={primaryId} onChange={e=>{const nextPrimary=e.target.value;setProfileId(nextPrimary);setProfileIds(previous=>Array.from({length:count},(_,index)=>previous[index]===nextPrimary?"":previous[index]||""));setSaved(false)}}><option value="">請選擇資料</option>{profiles.filter((p:any)=>p.profile_type==="person").map((p:any)=><option key={p.id} value={p.id} disabled={p.id!==primaryId&&ids.includes(p.id)}>{p.name}（{p.relationship_detail||p.relationship}）</option>)}</select></label><b>請選擇要觀看的對象（共 {count} 位）</b>{Array.from({length:count},(_,i)=>{const id=ids[i]||"";return <span key={`${detail.id}-target-${i}`}>{chooser(id,i)}</span>})}{hasDuplicate&&<em>同一位人不能重複選擇</em>}</div>:newbornNaming?<div className="extraFields newbornPeople">{personSelect(extra.mother_id,"mother_id","請選擇寶寶的媽媽")}{personSelect(extra.father_id,"father_id","請選擇寶寶的爸爸")}{personSelect(extra.baby_id,"baby_id","請選擇寶寶")}</div>:<label>{company?"請選擇公司負責人":code==="deceased-relative"?"請選擇過世親友":code==="infant-spirit"?"請選擇孩子的媽媽":"這個項目是為誰諮詢？"}<select disabled={locked} value={profileId} onChange={e=>{setProfileId(e.target.value);if(code==="infant-spirit"){const p=profiles.find((x:any)=>x.id===e.target.value);setExtra({...extra,pregnancy_losses:p?.pregnancy_losses||[{date:"",lunar:"",notes:""}]})}setSaved(false)}}><option value="">請選擇資料</option>{allowed.filter((p:any)=>code!=="infant-spirit"||p.gender==="女").map((p:any)=><option key={p.id} value={p.id}>{p.name}（{p.relationship_detail||p.relationship}）</option>)}</select></label>}
 {code==="infant-spirit"&&<div className="extraFields">{(extra.pregnancy_losses||[{date:"",lunar:"",notes:""}]).map((loss:any,i:number)=><div className="lossDate" key={i}><label>國曆流產日期<input type="date" value={loss.date||""} onChange={e=>{const list=[...(extra.pregnancy_losses||[])];list[i]={...loss,date:e.target.value,lunar:lunarProfile(e.target.value).lunar_birth_text};change("pregnancy_losses",list)}}/></label><label>農曆日期<input readOnly value={loss.lunar||""}/></label><label>備註<textarea placeholder="例如：只記得年份" value={loss.notes||""} onChange={e=>{const list=[...(extra.pregnancy_losses||[])];list[i]={...loss,notes:e.target.value};change("pregnancy_losses",list)}}/></label></div>)}{sub.includes("兩位")&&<button onClick={()=>change("pregnancy_losses",[...(extra.pregnancy_losses||[]),{date:"",lunar:"",notes:""}])}>＋增加一筆流產日期</button>}</div>}
 {company&&<div className="extraFields"><p>為了幫您的公司選出最合適的名稱，請協助填寫以下資訊：</p>{sub.includes("公司改名")&&<label>公司目前名字（或舊名）<input value={extra.old_name||""} onChange={e=>change("old_name",e.target.value)}/></label>}<label>主要業務與產品<textarea placeholder="例如：簡單說明公司是做什麼的、主要賣什麼或提供什麼服務即可" value={extra.business||""} onChange={e=>change("business",e.target.value)}/></label><label>公司經營模式<select value={extra.mode||""} onChange={e=>change("mode",e.target.value)}><option value="">請選擇</option><option value="sole">獨資（自己一人開）</option><option value="partners">合夥（有其他股東）</option></select></label>{extra.mode==="partners"&&<label>請選擇其他合夥人<select value={extra.partner||""} onChange={e=>change("partner",e.target.value)}><option value="">請選擇</option>{profiles.filter((p:any)=>p.profile_type==="person").map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label>命名喜好與禁忌<textarea value={extra.preferences||""} onChange={e=>change("preferences",e.target.value)}/></label><label>有沒有特別喜歡或想放進去的字？<input value={extra.favorite_words||""} onChange={e=>change("favorite_words",e.target.value)}/></label><label>其他備註<textarea value={extra.notes||""} onChange={e=>change("notes",e.target.value)}/></label></div>}
 {datePick&&<div className="extraFields"><label>這次是要擇什麼日子呢？<select value={extra.purpose||""} onChange={e=>change("purpose",e.target.value)}>{["","結婚／登記","手術／開刀","開工／開業","搬家／入宅","動土／修造","簽約／交易","提車／交車","安神／立壇","出行／遠行","喪葬／安葬","其他"].map(x=><option key={x}>{x||"請選擇"}</option>)}</select></label>{extra.purpose==="其他"&&<label>其他用途<input value={extra.other_purpose||""} onChange={e=>change("other_purpose",e.target.value)}/></label>}<label>請說明您目前的狀況<textarea value={extra.situation||""} onChange={e=>change("situation",e.target.value)}/></label><label>指定日期範圍、忌諱或注意事項<textarea value={extra.date_range||""} onChange={e=>change("date_range",e.target.value)}/></label><label>地點（若無可不填）<input value={extra.location||""} onChange={e=>change("location",e.target.value)}/></label><label>其他想補充的說明或狀況<textarea value={extra.notes||""} onChange={e=>change("notes",e.target.value)}/></label></div>}
 {newbornNaming&&<div className="extraFields"><label>是否有特別想用的字或喜歡的讀音？<textarea value={extra.preferred_characters||""} onChange={e=>change("preferred_characters",e.target.value)}/></label><label>對名字的風格有沒有什麼想像？<textarea placeholder="例如：想要響亮一點、優雅一點，還是有想避開的感覺？" value={extra.name_style||""} onChange={e=>change("name_style",e.target.value)}/></label><label>是否有禁忌或避諱的字或諧音？<textarea value={extra.name_taboo||""} onChange={e=>change("name_taboo",e.target.value)}/></label></div>}
 {code==="deceased-relative"&&<div className="extraFields"><label>目前的困擾或遺憾<textarea placeholder="例如：夢到對方感到不安、執著於某句沒說出口的話、對葬禮或後事安排感到疑慮" value={extra.current_regret||""} onChange={e=>change("current_regret",e.target.value)}/></label><label>這次諮詢最希望獲得什麼<textarea placeholder="例如：確認對方現在過得好不好？" value={extra.consultation_goal||""} onChange={e=>change("consultation_goal",e.target.value)}/></label></div>}
 {home&&<div className="extraFields"><label>本次諮詢的主要目的<textarea placeholder="例如：購屋前評估、裝修格局調整、搬入後想改善運勢…" value={extra.home_purpose||""} onChange={e=>change("home_purpose",e.target.value)}/></label><label>目前住起來最困擾的問題<textarea placeholder="例如：睡眠不好、頻繁吵架、財運受阻、身體欠安…" value={extra.home_problem||""} onChange={e=>change("home_problem",e.target.value)}/></label></div>}
 {code==="infant-spirit"&&<div className="extraFields"><label>目前的心理或生活狀況<textarea placeholder="例如：經常夢見、身體長期不適、心理無法放下、情緒焦慮、感情或事業不順等" value={extra.current_condition||""} onChange={e=>change("current_condition",e.target.value)}/></label><label>過去是否曾處理過<textarea placeholder="例如：是否做過超度、立牌位或相關儀式？" value={extra.previous_handling||""} onChange={e=>change("previous_handling",e.target.value)}/></label><label>這次最希望獲得的協助<textarea placeholder="例如：了解寶寶現況、尋求超度圓滿的方式" value={extra.assistance_goal||""} onChange={e=>change("assistance_goal",e.target.value)}/></label></div>}
 {lawsuit&&<div className="extraFields"><label>官司／糾紛類型<select value={extra.lawsuit_type||""} onChange={e=>change("lawsuit_type",e.target.value)}>{["","詐騙","債務","離婚","合約","侵權","傷害","交通事故","其他"].map(x=><option key={x}>{x||"請選擇"}</option>)}</select></label>{extra.lawsuit_type==="其他"&&<label>其他糾紛類型<input value={extra.other_lawsuit_type||""} onChange={e=>change("other_lawsuit_type",e.target.value)}/></label>}<label>目前訴訟進度<select value={extra.lawsuit_progress||""} onChange={e=>change("lawsuit_progress",e.target.value)}>{["","偵查中","收到傳票","準備開庭","其他"].map(x=><option key={x}>{x||"請選擇"}</option>)}</select></label>{extra.lawsuit_progress==="其他"&&<label>其他訴訟進度<input value={extra.other_lawsuit_progress||""} onChange={e=>change("other_lawsuit_progress",e.target.value)}/></label>}<label>下次開庭或調解日期<input type="date" value={extra.next_court_date||""} onChange={e=>change("next_court_date",e.target.value)}/></label><label>事件簡述與爭議點<textarea placeholder="請用 2～3 句話簡單說明事情經過，以及雙方目前卡住的地方" value={extra.dispute_summary||""} onChange={e=>change("dispute_summary",e.target.value)}/></label><label>目前是否有專業人士或他人協助<textarea placeholder="例如：已有委任律師、親友協調中，或是完全獨自面對" value={extra.professional_help||""} onChange={e=>change("professional_help",e.target.value)}/></label><label>本次最想解答的核心問題<textarea placeholder="例如：這場官司勝算高嗎？該選擇和解還是告到底？身邊會出現幫忙的貴人嗎？" value={extra.core_question||""} onChange={e=>change("core_question",e.target.value)}/></label></div>}
 {(relation||marriage)?<div className="targetQuestionGroups">{ids.filter(Boolean).map((id:string)=>{const primaryPerson=profiles.find((p:any)=>p.id===primaryId),person=profiles.find((p:any)=>p.id===id),left=primaryPerson?.relationship==="本人"?"我":`「${primaryPerson?.name||"諮詢者"}」`,right=person?.relationship==="本人"?"我":`「${person?.name||"這位對象"}」`,list=targetQuestions[id]?.length?targetQuestions[id]:[""],relationshipData=extra.relationship_details?.[id]||{},changeRelationship=(key:string,value:string)=>change("relationship_details",{...(extra.relationship_details||{}),[id]:{...relationshipData,[key]:value}});return <div className="targetQuestionBlock" key={id}>{marriage&&<div className="extraFields relationshipFields"><h3>請選擇與「{person?.name||"這位對象"}」的關係狀態</h3><label>目前關係狀態<select value={relationshipData.relationship_status||""} onChange={e=>changeRelationship("relationship_status",e.target.value)}>{["","單戀中","交往中","情侶吵架","分手想復合","曖昧卡住","複雜關係","其他"].map(x=><option key={x}>{x||"請選擇"}</option>)}</select></label><label>這段關係多久了？<input value={relationshipData.relationship_duration||""} onChange={e=>changeRelationship("relationship_duration",e.target.value)}/></label><label>這次最想解決的事件？<textarea placeholder="最近發生了什麼具體的事情，讓你決定來尋求建議？" value={relationshipData.main_event||""} onChange={e=>changeRelationship("main_event",e.target.value)}/></label><label>你最希望達成的目標？<textarea placeholder="例如：想挽回、想知道要不要停損、想改善溝通、想了解對方的真實想法" value={relationshipData.relationship_goal||""} onChange={e=>changeRelationship("relationship_goal",e.target.value)}/></label></div>}<QuestionFields title={`關於${left}與${right}的${relation?"前世關係":"感情問題"}，我想問`} questions={list} locked={locked} change={(next:string[])=>{setTargetQuestions({...targetQuestions,[id]:next});setSaved(false)}}/></div>})}</div>:<QuestionFields title="想詢問的問題" questions={questions} locked={locked} change={(next:string[])=>{setQuestions(next);setSaved(false)}}/>}<button disabled={locked||(relation||marriage?(!primaryId||ids.some(x=>!x)||hasDuplicate):newbornNaming?(!extra.mother_id||!extra.father_id||!extra.baby_id):!profileId)} onClick={async()=>{const primary=(relation||marriage)?primaryId:newbornNaming?extra.baby_id:profileId,allQuestions=(relation||marriage)?ids.flatMap((id:string)=>targetQuestions[id]?.length?targetQuestions[id]:[""]):questions,nextExtra=(relation||marriage)?{...extra,target_questions:targetQuestions}:extra;setSaved(true);setOpen(false);if(!await save(detail.id,primary,allQuestions,(relation||marriage)?[primary,...ids]:newbornNaming?[extra.mother_id,extra.father_id,extra.baby_id]:undefined,nextExtra)){setSaved(false);setOpen(true)}}}>{locked?"已送出":"儲存這個項目"}</button></article>
}
function hasCount(text:string,count:number){const patterns=count===3?["3人","三人","3位","三位","共3","共 3","共三","三個","three"]:["2人","兩人","二人","2位","兩位","二位","共2","共 2","共兩","共二","兩個","二個","two"];return patterns.some(value=>text.toLowerCase().includes(value.toLowerCase()))}
function QuestionFields({title,questions,locked,change}:any){const [limit,setLimit]=useState(false);return <div className="questions"><b>{title}</b>{questions.map((q:string,i:number)=><textarea disabled={locked} key={i} placeholder="輸入你想問的問題，也可點下方新增問題" value={q} onChange={e=>change(questions.map((x:string,n:number)=>n===i?e.target.value:x))}/>)}{!locked&&<button type="button" className="addQuestion" onClick={()=>{if(questions.length>=3){setLimit(true);return}change([...questions,""]);setLimit(false)}}>＋新增其他問題</button>}{limit&&<small className="questionLimit">已超過上限，每位對象最多可填寫三個問題</small>}</div>}
