"use client";
import { useEffect, useMemo, useState } from "react";
import QuickConsultationReply from "../QuickConsultationReply";
import "../style.css";
type DriveDocument={id:string;name:string;modifiedTime:string;webViewLink:string};
type Detected={slotIndex:number;label:string;itemCode:string};
const categories=[["overall-fortune","整體運勢"],["personal-romance","感情運勢"],["marriage-bazi","雙人關係與緣份（舊名：合八字）"],["health","身體健康"],["date-time-selection","擇日／擇時"],["past-life-personal","前世因果（個人）"],["past-life-relationship","與他人前世關係"],["infant-spirit","嬰靈"],["deceased-relative","過世親人"],["deceased-pet","過世寵物"],["spiritual-interference","靈擾／卡陰"],["home-energy","居家風水"],["lawsuit-benefactor","官司／貴人"],["naming","命名"]] as const;
const categoryLabel=(code:string)=>categories.find(([value])=>value===code)?.[1]||code;
export default function ExternalQuickWritePage(){
 const[documents,setDocuments]=useState<DriveDocument[]>([]),[selectedId,setSelectedId]=useState(""),[category,setCategory]=useState(""),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[detecting,setDetecting]=useState(false),[detected,setDetected]=useState<Detected[]>([]),[error,setError]=useState(""),[open,setOpen]=useState(false),[syncing,setSyncing]=useState(false),[syncMessage,setSyncMessage]=useState("");
 const selected=documents.find(x=>x.id===selectedId),filtered=useMemo(()=>documents.filter(x=>x.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())),[documents,query]);
 async function choose(id:string){setSelectedId(id);setCategory("");setOpen(false);setDetected([]);setDetecting(true);setError("");try{const r=await fetch(`/api/staff/external-consultation-docs?documentId=${encodeURIComponent(id)}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"辨識失敗");const rows:Detected[]=j.detected||[];setDetected(rows);if(rows.length===1)setCategory(rows[0].itemCode)}catch(e){setError(e instanceof Error?e.message:"辨識失敗")}finally{setDetecting(false)}}
 useEffect(()=>{void(async()=>{try{const requested=new URLSearchParams(location.search).get("documentId")||"",r=await fetch("/api/staff/external-consultation-docs",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"讀取失敗");setDocuments(j.documents||[]);if(requested&&(j.documents||[]).some((x:DriveDocument)=>x.id===requested))await choose(requested)}catch(e){setError(e instanceof Error?e.message:"讀取失敗")}finally{setLoading(false)}})()},[]);
 async function syncButtons(){setSyncing(true);setSyncMessage("");setError("");try{const r=await fetch("/api/staff/external-consultation-docs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"sync_buttons"})}),j=await r.json();if(!r.ok)throw new Error(j.error||"更新按鈕失敗");setSyncMessage(`已處理 ${j.updated} 份舊諮詢單`)}catch(e){setError(e instanceof Error?e.message:"更新按鈕失敗")}finally{setSyncing(false)}}
 return <main className="externalQuickWritePage"><header><div><small>非預約系統建立的文件</small><h1>外部諮詢單快速寫單</h1><p>只辨識「諮詢結果輸出區」，不會讀取客人的提問來猜測項目。</p></div><div className="externalHeaderActions"><button disabled={syncing} onClick={()=>void syncButtons()}>{syncing?"處理中…":"替所有舊單補上快速寫單按鈕"}</button><a href="/staff">返回預約後台</a>{syncMessage&&<strong>{syncMessage}</strong>}</div></header>{error&&<div className="externalQuickWriteError">{error}</div>}<section className="externalQuickWriteGrid"><aside><label>搜尋文件<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="輸入姓名或文件名稱"/></label><div className="externalDocumentList">{loading?<p>正在讀取 Google Drive…</p>:filtered.map(doc=><button type="button" className={selectedId===doc.id?"active":""} key={doc.id} onClick={()=>void choose(doc.id)}><b>{doc.name}</b><small>{doc.modifiedTime?new Date(doc.modifiedTime).toLocaleString("zh-TW",{timeZone:"Asia/Taipei"}):"未知時間"}</small></button>)}</div></aside><article>{selected?<><div className="externalEditorTitle"><div><small>目前文件</small><h2>{selected.name}</h2></div><a href={selected.webViewLink} target="_blank" rel="noreferrer">開啟 Google 文件</a></div>{detecting?<p>正在辨識結果輸出區…</p>:<><div className="externalDetected"><h3>偵測到的諮詢項目</h3>{detected.length?detected.map(row=><button key={`${row.slotIndex}-${row.itemCode}`} className={category===row.itemCode?"active":""} onClick={()=>{setCategory(row.itemCode);setOpen(false)}}><b>{row.label}</b><span>{categoryLabel(row.itemCode)}</span></button>):<p>這份舊單找不到可辨識的結果分類，請在下方手動選擇。</p>}</div><label className="externalCategorySelect">手動更改項目（備用）<select value={category} onChange={e=>{setCategory(e.target.value);setOpen(false)}}><option value="">請選擇諮詢項目</option>{categories.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><button type="button" className="externalOpenQuickReply" disabled={!category} onClick={()=>setOpen(true)}>✦ 開始點選快速寫單</button><p className="externalNoSendNotice">只會寫入這份 Google 文件，不會建立預約、傳送 LINE 或移動文件。</p></>}</>:<div className="externalQuickWriteEmpty"><b>請先選擇一份諮詢單</b></div>}</article></section>{open&&selected&&category&&<QuickConsultationReply bookingNo="EXTERNAL" documentId={selected.id} externalItemCode={category} onClose={()=>setOpen(false)}/>}</main>;
}
