"use client";
import { useEffect, useState } from "react";
import QuickConsultationReply from "../QuickConsultationReply";
import "../style.css";
type DriveDocument={id:string;name:string;webViewLink:string};
type Detected={slotIndex:number;label:string;itemCode:string};
const currentName:Record<string,string>={"marriage-bazi":"雙人關係與緣份","past-life-relationship":"與他人前世關係","spiritual-interference":"外靈干擾","past-life-personal":"前世因果（個人）","deceased-relative":"過世親人","overall-fortune":"整體運勢","home-energy":"陽宅","lawsuit-benefactor":"官司","personal-romance":"個人感情運","infant-spirit":"無緣孩子","deceased-pet":"過世寵物","health":"身體健康","date-time-selection":"擇日／擇時","naming":"命名"};
export default function ExternalQuickWritePage(){
 const[document,setDocument]=useState<DriveDocument|null>(null),[detected,setDetected]=useState<Detected[]>([]),[selected,setSelected]=useState<Detected|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{void(async()=>{try{const documentId=new URLSearchParams(location.search).get("documentId")||"";if(!documentId)throw new Error("這個連結缺少 Google 諮詢單資料");const listResponse=await fetch("/api/staff/external-consultation-docs",{cache:"no-store"}),list=await listResponse.json();if(!listResponse.ok)throw new Error(list.error||"讀取失敗");const found=(list.documents||[]).find((entry:DriveDocument)=>entry.id===documentId);if(!found)throw new Error("找不到這份諮詢單，請確認文件仍在指定資料夾內");setDocument(found);const detectResponse=await fetch(`/api/staff/external-consultation-docs?documentId=${encodeURIComponent(documentId)}`,{cache:"no-store"}),result=await detectResponse.json();if(!detectResponse.ok)throw new Error(result.error||"辨識失敗");const rows:Detected[]=result.detected||[];setDetected(rows);if(rows.length===1)setSelected(rows[0])}catch(value){setError(value instanceof Error?value.message:"讀取失敗")}finally{setLoading(false)}})()},[]);
 if(selected&&document)return <QuickConsultationReply bookingNo="EXTERNAL" documentId={document.id} externalItemCode={selected.itemCode} externalSlotIndex={selected.slotIndex} standalone onClose={()=>setSelected(null)}/>;
 return <main className="externalDirectWritePage"><header><div><small>阿嫂快速寫單</small><h1>{document?.name||"外部諮詢單"}</h1><p>選擇要填寫的結果項目，下一頁即可點選標籤、自動產生內容並寫入。</p></div>{document&&<a href={document.webViewLink} target="_blank" rel="noreferrer">回到 Google 諮詢單</a>}</header>{loading?<section className="externalDirectStatus">正在辨識結果輸出區…</section>:error?<section className="externalDirectError"><b>{error}</b><a href="/staff">返回預約後台登入或檢查</a></section>:<section className="externalDirectItems"><h2>要快速寫入哪一個項目？</h2>{detected.length?detected.map((row,index)=><button key={`${row.slotIndex}-${row.itemCode}`} onClick={()=>setSelected(row)}><span>{index+1}</span><div><b>{row.label}</b>{currentName[row.itemCode]&&currentName[row.itemCode]!==row.label&&<small>對應：{currentName[row.itemCode]}</small>}</div><strong>開始快速寫單 →</strong></button>):<div className="externalDirectError"><b>這份文件的結果輸出區找不到已知項目名稱。</b><p>系統沒有讀取客人的問題猜測，因此不會冒險寫入。</p></div>}</section>}</main>;
}
