"use client";
import { useEffect, useMemo, useState } from "react";
import QuickConsultationReply from "../QuickConsultationReply";
import "../style.css";
type DriveDocument={id:string;name:string;modifiedTime:string;webViewLink:string};
const categories=[["overall-fortune","整體運勢"],["personal-romance","感情運勢"],["marriage-bazi","雙人關係與緣份"],["health","身體健康"],["date-time-selection","擇日／擇時"],["past-life-personal","前世因果（個人）"],["past-life-relationship","與他人前世關係"],["infant-spirit","嬰靈"],["deceased-relative","過世親人"],["deceased-pet","過世寵物"],["spiritual-interference","靈擾／卡陰"],["home-energy","居家風水"],["lawsuit-benefactor","官司／貴人"],["naming","命名"]] as const;
export default function ExternalQuickWritePage(){
 const[documents,setDocuments]=useState<DriveDocument[]>([]),[selectedId,setSelectedId]=useState(""),[category,setCategory]=useState(""),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false);
 const selected=documents.find(x=>x.id===selectedId),filtered=useMemo(()=>documents.filter(x=>x.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())),[documents,query]);
 useEffect(()=>{void(async()=>{try{const r=await fetch("/api/staff/external-consultation-docs",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"讀取失敗");setDocuments(j.documents||[])}catch(e){setError(e instanceof Error?e.message:"讀取失敗")}finally{setLoading(false)}})()},[]);
 return <main className="externalQuickWritePage"><header><div><small>非預約系統建立的文件</small><h1>外部諮詢單快速寫單</h1><p>選擇舊諮詢單與項目，再用點選固定句快速組成結果。不會傳送 LINE。</p></div><a href="/staff">返回預約後台</a></header>{error&&<div className="externalQuickWriteError">{error}</div>}<section className="externalQuickWriteGrid"><aside><label>搜尋文件<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="輸入姓名或文件名稱"/></label><div className="externalDocumentList">{loading?<p>正在讀取 Google Drive…</p>:filtered.map(doc=><button type="button" className={selectedId===doc.id?"active":""} key={doc.id} onClick={()=>{setSelectedId(doc.id);setOpen(false)}}><b>{doc.name}</b><small>{doc.modifiedTime?new Date(doc.modifiedTime).toLocaleString("zh-TW",{timeZone:"Asia/Taipei"}):"未知時間"}</small></button>)}</div></aside><article>{selected?<><div className="externalEditorTitle"><div><small>目前文件</small><h2>{selected.name}</h2></div><a href={selected.webViewLink} target="_blank" rel="noreferrer">開啟 Google 文件</a></div><label className="externalCategorySelect">這份諮詢單的項目<select value={category} onChange={e=>{setCategory(e.target.value);setOpen(false)}}><option value="">請選擇諮詢項目</option>{categories.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><button type="button" className="externalOpenQuickReply" disabled={!category} onClick={()=>setOpen(true)}>✦ 開始點選快速寫單</button><p className="externalNoSendNotice">只會寫入這份 Google 文件，不會建立預約、傳送 LINE 或移動文件。</p></>:<div className="externalQuickWriteEmpty"><b>請先選擇一份諮詢單</b><p>只會顯示指定資料夾內的 Google 文件。</p></div>}</article></section>{open&&selected&&category&&<QuickConsultationReply bookingNo="EXTERNAL" documentId={selected.id} externalItemCode={category} onClose={()=>setOpen(false)}/>}</main>;
}
