"use client";
import {useEffect,useRef,useState} from 'react';
type Choice={slotIndex:number;questionNumber:number;question:string;profileName:string;options:string[];labels?:string[];mode?:string};
export default function AiAnswerChoices({fingerprint,generate,onChoose}:{fingerprint:string;generate:()=>Promise<{choices:Choice[]}>;onChoose:(slot:number,answer:string)=>boolean}){
 const [choices,setChoices]=useState<Choice[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Record<number,number>>({}),current=useRef(fingerprint),request=useRef(0);current.current=fingerprint;
 useEffect(()=>{setChoices([]);setSelected({});setError('');request.current++;setBusy(false)},[fingerprint]);
 async function run(){const source=current.current,id=++request.current;setBusy(true);setError('');try{const result=await generate();if(id===request.current&&source===current.current){setChoices(result.choices);setSelected({})}}catch(e){if(id===request.current)setError(e instanceof Error?e.message:'AI 回答產生失敗')}finally{if(id===request.current)setBusy(false)}}
 return <div className="aiAnswerChoices inlineAiAnswer"><button className="aiGenerateButton" type="button" disabled={busy} onClick={()=>void run()}>{busy?'AI 正在產生這題回答…':'✦ AI 產生這題的 3 種回答'}</button><p className="aiModeHint">有內容：依阿嫂判斷提供 3 種說法；無內容：提供正面、中性、負面草稿。</p>{error&&<p role="alert">{error}</p>}{choices.map(q=><article key={q.slotIndex}><p>{q.mode==='directions'?'正面／中性／負面判斷草稿，請阿嫂確認後選用。':'依阿嫂已寫內容產生，請選擇最適合的說法。'}</p><div>{q.options.map((answer,i)=><button type="button" key={i} aria-pressed={selected[q.slotIndex]===i} className={selected[q.slotIndex]===i?'selected':''} onClick={()=>{if(onChoose(q.slotIndex,answer))setSelected(c=>({...c,[q.slotIndex]:i}))}}><b>{q.labels?.[i]||`回答 ${i+1}`}{selected[q.slotIndex]===i?'・已填入':''}</b><span>{answer}</span><small>點選填入此題</small></button>)}</div></article>)}</div>;
}
