"use client";
import {useEffect,useRef,useState} from 'react';
type Choice={slotIndex:number;questionNumber:number;question:string;profileName:string;options:string[];labels?:string[];mode?:string};
type Direction='positive'|'neutral'|'negative';
export default function AiAnswerChoices({fingerprint,hasReference=false,label='阿嫂回覆',generate,onChoose}:{fingerprint:string;hasReference?:boolean;label?:string;generate:(direction?:Direction)=>Promise<{choices:Choice[]}>;onChoose:(slot:number,answer:string)=>boolean}){
 const [choices,setChoices]=useState<Choice[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Record<number,number>>({}),current=useRef(fingerprint),request=useRef(0);current.current=fingerprint;
 useEffect(()=>{setChoices([]);setSelected({});setError('');setOpen(false);request.current++;setBusy(false)},[fingerprint]);
 async function run(direction?:Direction){const source=current.current,id=++request.current;setBusy(true);setError('');setChoices([]);try{const result=await generate(direction);if(id===request.current&&source===current.current){setChoices(result.choices);setSelected({})}}catch(e){if(id===request.current)setError(e instanceof Error?e.message:'AI 回答產生失敗')}finally{if(id===request.current)setBusy(false)}}
 function activate(){setOpen(true);if(hasReference)void run();}
 return <div className="aiAnswerChoices inlineAiAnswer"><div className="aiReplyHeading"><b>{label}</b><button className="aiGenerateButton" type="button" disabled={busy} onClick={activate}>{busy?'產生中…':'✦ AI 建議回覆'}</button></div>{open&&<div className="aiReplySuggestions">{!hasReference&&<><p>先選擇判斷方向，再產生該方向的 3 個回覆。</p><div className="aiDirectionButtons">{([['positive','正面'],['neutral','中性'],['negative','負面']] as const).map(([value,text])=><button type="button" key={value} disabled={busy} onClick={()=>void run(value)}>{text}</button>)}</div></>}{error&&<p role="alert">{error}</p>}{choices.map(q=><article key={q.slotIndex}><p>{q.mode==='directions'?'請選擇最適合的草稿，點選後直接填入下方回答框。':'優先參考阿嫂已寫內容；點選後直接填入下方回答框。'}</p><div>{q.options.map((answer,i)=><button type="button" key={i} aria-pressed={selected[q.slotIndex]===i} className={selected[q.slotIndex]===i?'selected':''} onClick={()=>{if(onChoose(q.slotIndex,answer))setSelected(c=>({...c,[q.slotIndex]:i}))}}><b>{q.labels?.[i]||`建議 ${i+1}`}{selected[q.slotIndex]===i?'・已填入':''}</b><span>{answer}</span><small>點選填入回答</small></button>)}</div></article>)}</div>}</div>;
}
