"use client";
import {useState} from 'react';
import {annualAges,annualFortuneGroups,composeAnnual,parseAnnual,annualText,toggleAnnualCodes,type AnnualState} from '@/lib/annual-fortune';
export default function AnnualFortuneEditor({startAge,value,state,onChange,onSave,disabled=false}:{startAge:number;value:string;state?:AnnualState;onChange:(text:string,state:AnnualState,age:number)=>void;onSave?:(age:number)=>Promise<void>;disabled?:boolean}){
 const ages=annualAges(startAge),[active,setActive]=useState(startAge),[variant,setVariant]=useState(0),[category,setCategory]=useState(0),[saving,setSaving]=useState(false),[saved,setSaved]=useState(''),[error,setError]=useState('');const rows=state||parseAnnual(value),age=ages.includes(active)?active:ages[0],row=rows[String(age)]||{codes:[],text:''};
 const update=(next:AnnualState)=>{setSaved('');onChange(annualText(ages,next),next,age)};
 function toggle(code:string){const codes=toggleAnnualCodes(row.codes,code);update({...rows,[age]:{...row,codes,text:row.manual?row.text:composeAnnual(codes,variant+age)}});}
 async function save(){if(!onSave)return;setSaving(true);setError('');try{await onSave(age);setSaved(`${age}歲已寫入諮詢單`)}catch(e){setError(e instanceof Error?e.message:'寫入失敗，內容已保留')}finally{setSaving(false)}}
 if(!ages.length)return <section className="annualFortuneEditor"><p>找不到文件的年齡列，請先確認【流年運勢】內容。</p></section>;
 const group=annualFortuneGroups[category];
 return <section className="annualFortuneEditor"><h3>流年運勢・{ages[0]}～{ages.at(-1)}歲（共 {ages.length} 年）</h3><p>直接對應諮詢單的年齡。每年獨立複選、修改，再寫入該年冒號後。</p><div className="annualEditorLayout"><nav aria-label="選擇流年年齡">{ages.map(n=><button type="button" key={n} className={n===age?'selected':''} disabled={saving||disabled} aria-pressed={n===age} onClick={()=>{setActive(n);setSaved('');setError('')}}>{n}歲 <small>{rows[n]?.text?'✓ 已填':'待填'}</small></button>)}</nav><div><h4>{age}歲・請選擇判斷分類</h4><div className="annualCategoryTabs" role="group" aria-label="流年選項分類">{annualFortuneGroups.map((g,index)=><button type="button" key={g.title} aria-pressed={index===category} className={index===category?'selected':''} onClick={()=>setCategory(index)}>{g.title.replace('（只加入阿嫂明確選取的內容）','')} <small>{g.options.filter(o=>row.codes.includes(o.code)).length||''}</small></button>)}</div><fieldset disabled={saving||disabled}><legend>{group.title}</legend><div>{group.options.map(o=><button type="button" key={o.code} aria-pressed={row.codes.includes(o.code)} className={row.codes.includes(o.code)?'selected':''} onClick={()=>toggle(o.code)}>{o.label}</button>)}</div></fieldset><p className="annualSelectionHint">可跨分類複選；同一件事的相反判斷會互相替換。</p>{row.codes.length>0&&<div className="annualSelectedChips">{annualFortuneGroups.flatMap(g=>g.options).filter(o=>row.codes.includes(o.code)).map(o=><button type="button" key={o.code} disabled={saving||disabled} onClick={()=>toggle(o.code)}>{o.label} ×</button>)}</div>}<label className="annualTextLabel">{age}歲：<textarea disabled={saving||disabled} value={row.text} rows={4} onChange={e=>update({...rows,[age]:{...row,text:e.target.value,manual:true}})}/></label>{row.manual&&<p>已保留自行修改的文字；調整選項後，可按重新組合。</p>}<div className="annualWriteActions"><button type="button" disabled={!row.codes.length||saving||disabled} onClick={()=>{const next=variant+1;setVariant(next);update({...rows,[age]:{...row,text:composeAnnual(row.codes,next+age),manual:false}})}}>依選項重新組合／換個說法</button>{onSave&&<button type="button" className="annualSaveButton" disabled={saving||disabled} onClick={()=>void save()}>{saving?'寫入中…':`寫入 ${age}歲 到諮詢單`}</button>}</div>{saved&&<p role="status">✓ {saved}</p>}{error&&<p role="alert">{error}</p>}<details><summary>查看 {ages.length} 年整體預覽</summary><pre>{annualText(ages,rows)}</pre></details></div></div></section>;
}
