"use client";
import {useState} from "react";
import {annualAges,annualFortuneGroups,composeAnnual,parseAnnual,annualText,type AnnualState} from "@/lib/annual-fortune";
export default function AnnualFortuneEditor({startAge,value,state,onChange}:{startAge:number;value:string;state?:AnnualState;onChange:(text:string,state:AnnualState)=>void}){
 const ages=annualAges(startAge),[active,setActive]=useState(startAge),[variant,setVariant]=useState(0);const rows=state||parseAnnual(value),age=ages.includes(active)?active:ages[0],row=rows[String(age)]||{codes:[],text:""};
 const update=(next:AnnualState)=>onChange(annualText(ages,next),next);
 function toggle(code:string){const codes=row.codes.includes(code)?row.codes.filter(c=>c!==code):[...row.codes,code];update({...rows,[age]:{...row,codes,text:row.manual?row.text:composeAnnual(codes,variant+age)}});}
 if(!ages.length)return <section className="annualFortuneEditor"><p>找不到目前虛歲，請先確認諮詢者生日或文件資料。</p></section>;
 return <section className="annualFortuneEditor"><h3>流年運勢・{ages[0]}～{ages.at(-1)}歲（共 {ages.length} 年）</h3><p>逐年複選，再確認文字。沒有選擇的內容不會自動加入。</p><div className="annualEditorLayout"><nav aria-label="選擇流年年齡">{ages.map(n=><button key={n} className={n===age?"selected":""} aria-pressed={n===age} onClick={()=>setActive(n)}>{n}歲 <small>{rows[n]?.text?"✓ 已填":"待填"}</small></button>)}</nav><div><h4>{age}歲的選項</h4>{annualFortuneGroups.map(g=><fieldset key={g.title}><legend>{g.title}</legend><div>{g.options.map(o=><button key={o.code} aria-pressed={row.codes.includes(o.code)} className={row.codes.includes(o.code)?"selected":""} onClick={()=>toggle(o.code)}>{o.label}</button>)}</div></fieldset>)}<label className="annualTextLabel">{age}歲內容（可直接修改）<textarea value={row.text} rows={4} onChange={e=>update({...rows,[age]:{...row,text:e.target.value,manual:true}})}/></label>{row.manual&&<p>已保留自行修改的文字；調整選項後，請按下方按鈕重新組合。</p>}<button disabled={!row.codes.length} onClick={()=>{const next=variant+1;setVariant(next);update({...rows,[age]:{...row,text:composeAnnual(row.codes,next+age),manual:false}})}}>依選項重新組合／換個說法</button><details><summary>查看 15 年整體預覽</summary><pre>{annualText(ages,rows)}</pre></details></div></div></section>;
}
