"use client";
import { useEffect, useState } from 'react';
type Person={line_user_id:string;display_name:string;full_name?:string;picture_url?:string;source?:string;note?:string};
export default function LineWatchlist(){
 const [open,setOpen]=useState(false),[items,setItems]=useState<Person[]>([]),[q,setQ]=useState(''),[people,setPeople]=useState<Person[]>([]),[selected,setSelected]=useState<Person|null>(null),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/staff/line-watchlist',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setItems(j.watchlist||[]);}catch(e){setMessage(String(e));}}
 useEffect(()=>{void load()},[]);
 async function search(){setBusy(true);setSelected(null);setPeople([]);setMessage('');try{const r=await fetch('/api/staff/line-contacts?q='+encodeURIComponent(q)),j=await r.json();if(!r.ok)throw Error(j.error);setPeople(j.people||[]);setMessage(j.warning||(!j.people?.length?'沒有符合的已知聯絡人。可同步 LINE 好友後再搜尋；不需要對方註冊。':''));}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 async function sync(){setBusy(true);try{let cursor='';do{const r=await fetch('/api/staff/line-contacts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({cursor})}),j=await r.json();if(!r.ok)throw Error(j.error);cursor=j.next||'';setMessage('正在同步 LINE 好友…');}while(cursor);setMessage('同步完成，請輸入名稱搜尋。');}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 async function save(){if(!selected)return;setBusy(true);try{const r=await fetch('/api/staff/line-watchlist',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lineUserId:selected.line_user_id,displayName:selected.display_name,note})}),j=await r.json();if(!r.ok)throw Error(j.error);setSelected(null);setNote('');setMessage('已加入通知名單');await load();}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 async function remove(p:Person){if(!confirm('確定移除 '+p.display_name+' 的通知？'))return;setBusy(true);try{const r=await fetch('/api/staff/line-watchlist?lineUserId='+encodeURIComponent(p.line_user_id),{method:'DELETE'}),j=await r.json();if(!r.ok)throw Error(j.error);await load();}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 return <section className="lineWatchlist"><header><h2>LINE 即時通知名單 <small>（{items.length} 位）</small></h2><button type="button" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'收合':'展開管理'}</button></header>{open&&<div>
 <p>搜尋名稱、核對頭像與帳號後加入；對方不必註冊預約系統。</p>
 <form className="lineWatchSearch" onSubmit={e=>{e.preventDefault();void search()}}><input aria-label="搜尋 LINE 名稱或本名" placeholder="輸入 LINE 名稱或本名" value={q} onChange={e=>{setQ(e.target.value);setSelected(null);setPeople([])}}/><button disabled={busy||!q.trim()}>搜尋</button><button type="button" disabled={busy} onClick={()=>void sync()}>同步 LINE 好友</button></form>
 <div className="lineWatchResults">{people.map(p=><button type="button" key={p.line_user_id} disabled={busy} onClick={()=>setSelected(p)}>{p.picture_url&&<img src={p.picture_url} alt=""/>}<span><b>{p.display_name}</b><small>{p.full_name} · {p.source} · 帳號末碼 {p.line_user_id.slice(-6)}</small></span></button>)}</div>
 {selected&&<div className="lineWatchConfirm"><b>要加入的是「{selected.display_name}」這位嗎？</b><p>帳號末碼：{selected.line_user_id.slice(-6)}</p><input aria-label="備註" placeholder="備註（選填）" value={note} onChange={e=>setNote(e.target.value)}/><button disabled={busy} onClick={()=>void save()}>確認加入通知名單</button><button disabled={busy} onClick={()=>setSelected(null)}>取消</button></div>}
 {message&&<p role="status">{message}</p>}<div className="lineWatchItems">{items.map(p=><article key={p.line_user_id}><div><b>{p.display_name}</b><small>{p.note||'未填備註'}</small></div><button disabled={busy} onClick={()=>void remove(p)}>移除</button></article>)}{!items.length&&<p>目前尚未設定通知對象。</p>}</div></div>}</section>;
}
