"use client";
import { useEffect, useMemo, useState } from "react";

type Topic={code:string;title:string;icon:string;options:{code:string;label:string}[]};
type Question={slotIndex:number;questionNumber:number;question:string;answer:string;itemCode:string;itemTitle:string;manualOnly:boolean};
type Draft={selections:Record<string,string>;phraseIds:string[];answer:string;completed?:boolean};
type ReplyData={bookingNo:string;customerName:string;questions:Question[];topics:Topic[];recommendedByQuestion:Record<string,string[]>;questionReplies:Record<string,Draft>;documentId:string;documentUrl:string};

export default function QuickConsultationReply({bookingNo,documentId,onClose}:{bookingNo:string;documentId:string;onClose:()=>void}){
  const [data,setData]=useState<ReplyData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[activeQuestion,setActiveQuestion]=useState(0),[activeCategory,setActiveCategory]=useState<Record<string,string>>({}),[drafts,setDrafts]=useState<Record<string,Draft>>({}),[busy,setBusy]=useState(false),[written,setWritten]=useState(false),[editing,setEditing]=useState(false);
  useEffect(()=>{fetch(`/api/staff/quick-reply?bookingNo=${encodeURIComponent(bookingNo)}&documentId=${encodeURIComponent(documentId)}`).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"讀取失敗");setData(result);setDrafts(result.questionReplies||{});setActiveCategory(Object.fromEntries((result.questions||[]).map((question:Question)=>[String(question.slotIndex),result.recommendedByQuestion?.[String(question.slotIndex)]?.[0]||result.topics?.[0]?.code||""])))}).catch(err=>setError(err instanceof Error?err.message:"讀取失敗")).finally(()=>setLoading(false))},[bookingNo,documentId]);
  const topicMap=useMemo(()=>new Map((data?.topics||[]).map(topic=>[topic.code,topic])),[data]);
  const question=data?.questions[activeQuestion],questionKey=String(question?.slotIndex??0),draft=drafts[questionKey]||{selections:{},phraseIds:[],answer:"",completed:false},categoryCode=activeCategory[questionKey]||"",category=topicMap.get(categoryCode),recommended=new Set(data?.recommendedByQuestion?.[questionKey]||[]);
  async function compose(nextSelections:Record<string,string>,reroll=false){if(!question||!Object.keys(nextSelections).length)return;setBusy(true);setError("");setWritten(false);try{const response=await fetch("/api/staff/quick-reply",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"compose",bookingNo,documentId,selections:nextSelections,previousPhraseIds:reroll?draft.phraseIds:[]})}),result=await response.json();if(!response.ok)throw new Error(result.error||"產生回覆失敗");setDrafts(current=>({...current,[questionKey]:{selections:nextSelections,phraseIds:result.phraseIds||[],answer:result.answer||"",completed:true}}));setEditing(false)}catch(err){setError(err instanceof Error?err.message:"產生回覆失敗")}finally{setBusy(false)}}
  function choose(optionCode:string){if(!category)return;const next={...draft.selections,[category.code]:optionCode};setDrafts(current=>({...current,[questionKey]:{...draft,selections:next,completed:false}}));void compose(next)}
  function removeCategory(){if(!category)return;const next={...draft.selections};delete next[category.code];setDrafts(current=>({...current,[questionKey]:{selections:next,phraseIds:[],answer:Object.keys(next).length?draft.answer:"",completed:false}}));if(Object.keys(next).length)void compose(next);else setEditing(false)}
  function selectQuestion(index:number){setActiveQuestion(index);setEditing(false);setError("");setWritten(false)}
  async function write(){if(!Object.values(drafts).some(row=>row.answer?.trim())||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/staff/quick-reply",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"write",bookingNo,documentId,questionReplies:drafts})}),result=await response.json();if(!response.ok)throw new Error(result.error||"寫入失敗");setWritten(true);setEditing(false)}catch(err){setError(err instanceof Error?err.message:"寫入失敗，內容已保留，請重新寫入")}finally{setBusy(false)}}
  return <div className="quickReplyBackdrop"><section className="quickReplyPanel" role="dialog" aria-modal="true"><header><div><h2>建立諮詢回覆</h2>{data&&<p>{data.customerName}｜{data.bookingNo}</p>}</div><button onClick={onClose} aria-label="關閉">×</button></header>
    {loading?<div className="quickReplyStatus">正在讀取客人問題與句庫…</div>:error&&!data?<div className="quickReplyStatus error"><b>無法開啟</b><p>{error}</p><button onClick={onClose}>返回後台</button></div>:data&&<div className="quickReplyBody">
      <section className="quickReplyQuestions"><h3>先點選要回答的問題</h3><div>{data.questions.map((entry,index)=>{const row=drafts[String(entry.slotIndex)],selected=index===activeQuestion,done=row?.completed===true;return <button key={entry.slotIndex} className={selected?"selected":""} onClick={()=>selectQuestion(index)}><span>{done?"✓":`Q${entry.questionNumber}`}</span><b><em>{entry.itemTitle}</em>{entry.question}</b><small>{done?"已完成回答":selected?"目前選取":"點此回答"}</small></button>})}</div></section>
      {question&&<>{!question.manualOnly&&<section className="quickReplyCategoryPicker"><h3>Q{question.questionNumber} 要判斷哪一類？</h3><p><b>{question.itemTitle}</b>{question.question}</p><div>{data.topics.map(topic=><button key={topic.code} className={`${categoryCode===topic.code?"active":""} ${draft.selections[topic.code]?"answered":""}`} onClick={()=>setActiveCategory(current=>({...current,[questionKey]:topic.code}))}><span>{topic.icon}</span>{topic.title}{recommended.has(topic.code)&&<small>預設</small>}{draft.selections[topic.code]&&<em>✓</em>}</button>)}</div></section>}
        {!question.manualOnly&&category&&<section className="quickReplyOptions"><h3>{category.icon} {category.title}</h3><div>{category.options.map(option=><button key={option.code} className={draft.selections[category.code]===option.code?"selected":""} onClick={()=>choose(option.code)} disabled={busy}>{draft.selections[category.code]===option.code&&<span>✓</span>}{option.label}</button>)}</div>{draft.selections[category.code]&&<button className="quickReplyRemoveCategory" onClick={removeCategory}>移除這一類判斷</button>}</section>}
        <section className="quickReplyPreview"><div><h3>Q{question.questionNumber} 回覆預覽</h3>{draft.answer&&<span>{editing||question.manualOnly?"直接修改中":"可繼續選其他分類"}</span>}</div>{editing||question.manualOnly?<textarea value={draft.answer} placeholder={question.manualOnly?"前世因果每個個案不同，請直接輸入阿嫂的回答。":""} onChange={event=>{const answer=event.target.value;setDrafts(current=>({...current,[questionKey]:{...draft,answer,completed:answer.trim().length>0}}))}} autoFocus/>:<p>{draft.answer||"請先選擇分類，再點選判斷結果。"}</p>}{error&&<div className="quickReplyError">{error}</div>}{written&&<div className="quickReplySuccess">✅ 已成功寫入 Google 諮詢單的 A{question.questionNumber}</div>}<div className="quickReplyPreviewActions">{!question.manualOnly&&<button disabled={!draft.answer||busy} onClick={()=>void compose(draft.selections,true)}>↻ 換一種說法</button>}<button disabled={!draft.answer||busy} onClick={()=>setEditing(value=>!value)}>✎ {editing?"完成修改":"自行修改"}</button></div></section>
      </>}
      <footer><button className="quickReplyWrite" disabled={!Object.values(drafts).some(row=>row.answer?.trim())||busy} onClick={()=>void write()}>{busy?"處理中…":written?"再次寫入更新":"確認寫入全部回答"}</button>{written&&<a href={data.documentUrl} target="_blank" rel="noreferrer">查看 Google 文件</a>}<button className="quickReplyCancel" onClick={onClose}>返回預約後台</button></footer>
    </div>}
  </section></div>
}
