"use client";
import {useEffect,useMemo,useState} from "react";
type Option={id:string;code:string;label:string};type Topic={code:string;title:string;icon:string;options:Option[]};
type Question={slotIndex:number;questionNumber:number;question:string;answer:string;itemCode:string;itemTitle:string;manualOnly:boolean};type Section={slotIndex:number;label:string;answer:string;itemCode:string;manualOnly:boolean};
type Draft={selections:Record<string,string>;phraseIds:string[];answer:string;completed?:boolean};type SectionDraft={optionIds:string[];phraseIds:string[];answer:string;completed?:boolean};
type ReplyData={bookingNo:string;customerName:string;questions:Question[];sections:Section[];topics:Topic[];recommendedByQuestion:Record<string,string[]>;recommendedBySection:Record<string,string[]>;questionReplies:Record<string,Draft>;sectionReplies:Record<string,SectionDraft>;documentUrl:string};
export default function QuickConsultationReply({bookingNo,documentId,onClose}:{bookingNo:string;documentId:string;onClose:()=>void}){
 const [data,setData]=useState<ReplyData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[view,setView]=useState<"section"|"question">("section"),[activeQuestion,setActiveQuestion]=useState(0),[activeSection,setActiveSection]=useState(0),[activeCategory,setActiveCategory]=useState<Record<string,string>>({}),[sectionCategory,setSectionCategory]=useState<Record<string,string>>({}),[drafts,setDrafts]=useState<Record<string,Draft>>({}),[sectionDrafts,setSectionDrafts]=useState<Record<string,SectionDraft>>({}),[busy,setBusy]=useState(false),[written,setWritten]=useState(false),[editing,setEditing]=useState(false);
 useEffect(()=>{fetch(`/api/staff/quick-reply?bookingNo=${encodeURIComponent(bookingNo)}&documentId=${encodeURIComponent(documentId)}`).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||"讀取失敗");setData(x);setDrafts(x.questionReplies||{});setSectionDrafts(x.sectionReplies||{});setActiveCategory(Object.fromEntries((x.questions||[]).map((q:Question)=>[String(q.slotIndex),x.recommendedByQuestion?.[String(q.slotIndex)]?.[0]||x.topics?.[0]?.code||""])));setSectionCategory(Object.fromEntries((x.sections||[]).map((s:Section)=>[String(s.slotIndex),x.recommendedBySection?.[String(s.slotIndex)]?.[0]||x.topics?.[0]?.code||""])));if(!(x.sections||[]).some((s:Section)=>!s.manualOnly))setView("question")}).catch(e=>setError(e instanceof Error?e.message:"讀取失敗")).finally(()=>setLoading(false))},[bookingNo,documentId]);
 const topicMap=useMemo(()=>new Map((data?.topics||[]).map(t=>[t.code,t])),[data]),sections=(data?.sections||[]).filter(s=>!s.manualOnly),section=sections[activeSection],sectionKey=String(section?.slotIndex??0),sectionDraft=sectionDrafts[sectionKey]||{optionIds:[],phraseIds:[],answer:"",completed:false},sectionTopic=topicMap.get(sectionCategory[sectionKey]||"");
 const question=data?.questions[activeQuestion],questionKey=String(question?.slotIndex??0),draft=drafts[questionKey]||{selections:{},phraseIds:[],answer:"",completed:false},categoryCode=activeCategory[questionKey]||"",category=topicMap.get(categoryCode),recommended=new Set(data?.recommendedByQuestion?.[questionKey]||[]);
 async function post(payload:any){const r=await fetch("/api/staff/quick-reply",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bookingNo,documentId,...payload})}),x=await r.json();if(!r.ok)throw new Error(x.error||"處理失敗");return x}
 async function compose(next:Record<string,string>,reroll=false){if(!question||!Object.keys(next).length)return;setBusy(true);setError("");setWritten(false);try{const x=await post({mode:"compose",selections:next,previousPhraseIds:reroll?draft.phraseIds:[]});setDrafts(c=>({...c,[questionKey]:{selections:next,phraseIds:x.phraseIds||[],answer:x.answer||"",completed:true}}));setEditing(false)}catch(e){setError(e instanceof Error?e.message:"產生回覆失敗")}finally{setBusy(false)}}
 async function composeSection(optionIds:string[],reroll=false){if(!section||!optionIds.length)return;setBusy(true);setError("");setWritten(false);try{const x=await post({mode:"compose_section",optionIds,previousPhraseIds:reroll?sectionDraft.phraseIds:[]});setSectionDrafts(c=>({...c,[sectionKey]:{optionIds,phraseIds:x.phraseIds||[],answer:x.answer||"",completed:true}}));setEditing(false)}catch(e){setError(e instanceof Error?e.message:"產生回覆失敗")}finally{setBusy(false)}}
 function choose(code:string){if(!category)return;const next={...draft.selections,[category.code]:code};setDrafts(c=>({...c,[questionKey]:{...draft,selections:next,completed:false}}));void compose(next)}
 function toggleOption(id:string){const next=sectionDraft.optionIds.includes(id)?sectionDraft.optionIds.filter(x=>x!==id):[...sectionDraft.optionIds,id];if(!next.length)return setSectionDrafts(c=>({...c,[sectionKey]:{optionIds:[],phraseIds:[],answer:"",completed:false}}));void composeSection(next)}
 function removeCategory(){if(!category)return;const next={...draft.selections};delete next[category.code];setDrafts(c=>({...c,[questionKey]:{selections:next,phraseIds:[],answer:Object.keys(next).length?draft.answer:"",completed:false}}));if(Object.keys(next).length)void compose(next)}
 async function write(){if(!hasAnswer||busy)return;setBusy(true);setError("");try{await post({mode:"write",questionReplies:drafts,sectionReplies:sectionDrafts});setWritten(true);setEditing(false)}catch(e){setError(e instanceof Error?e.message:"寫入失敗，內容已保留")}finally{setBusy(false)}}
 const hasAnswer=Object.values(drafts).some(r=>r.answer?.trim())||Object.values(sectionDrafts).some(r=>r.answer?.trim());
 const pickTarget=(kind:"section"|"question",index:number)=>{setView(kind);kind==="section"?setActiveSection(index):setActiveQuestion(index);setEditing(false);setError("");setWritten(false)};
 return <div className="quickReplyBackdrop"><section className="quickReplyPanel" role="dialog" aria-modal="true"><header><div><h2>建立諮詢回覆</h2>{data&&<p>{data.customerName}｜{data.bookingNo}</p>}</div><button onClick={onClose}>×</button></header>{loading?<div className="quickReplyStatus">正在讀取客人問題與句庫…</div>:error&&!data?<div className="quickReplyStatus error"><b>無法開啟</b><p>{error}</p><button onClick={onClose}>返回後台</button></div>:data&&<div className="quickReplyBody">
 <nav className="quickReplyModeTabs"><button className={view==="section"?"active":""} onClick={()=>setView("section")}>項目標籤回覆</button><button className={view==="question"?"active":""} onClick={()=>setView("question")}>客人問題 Q&amp;A</button></nav>
 {view==="section"&&<>{sections.length?<section className="quickReplyQuestions"><h3>先點選要填寫的項目標籤</h3><div>{sections.map((s,i)=>{const done=sectionDrafts[String(s.slotIndex)]?.completed===true;return <button key={s.slotIndex} className={i===activeSection?"selected":""} onClick={()=>pickTarget("section",i)}><span>{done?"✓":"項目"}</span><b>【{s.label}】</b><small>{done?"已完成回答":i===activeSection?"目前選取":"點此回答"}</small></button>})}</div></section>:<div className="quickReplyStatus">這份文件沒有可套用句庫的項目標籤。</div>}{section&&<><section className="quickReplyCategoryPicker"><h3>【{section.label}】常用命理回覆</h3><p>先選分類，再複選多個答案。</p><div>{data.topics.map(t=><button key={t.code} className={sectionTopic?.code===t.code?"active":""} onClick={()=>setSectionCategory(c=>({...c,[sectionKey]:t.code}))}><span>{t.icon}</span>{t.title}{data.recommendedBySection?.[sectionKey]?.includes(t.code)&&<small>預設</small>}</button>)}</div></section>{sectionTopic&&<section className="quickReplyOptions quickReplyMultiOptions"><h3>{sectionTopic.icon} {sectionTopic.title}（可複選）</h3><div>{sectionTopic.options.map(o=><button key={o.id} className={sectionDraft.optionIds.includes(o.id)?"selected":""} onClick={()=>toggleOption(o.id)} disabled={busy}>{sectionDraft.optionIds.includes(o.id)&&<span>✓</span>}{o.label}</button>)}</div></section>}<section className="quickReplyPreview"><div><h3>【{section.label}】回覆預覽</h3>{sectionDraft.answer&&<span>{editing?"直接修改中":"可繼續複選"}</span>}</div>{editing?<textarea value={sectionDraft.answer} onChange={e=>{const answer=e.target.value;setSectionDrafts(c=>({...c,[sectionKey]:{...sectionDraft,answer,completed:!!answer.trim()}}))}} autoFocus/>:<p>{sectionDraft.answer||"請先複選上方的常用命理回覆。"}</p>}<div className="quickReplyPreviewActions"><button disabled={!sectionDraft.answer||busy} onClick={()=>void composeSection(sectionDraft.optionIds,true)}>↻ 換一種說法</button><button disabled={!sectionDraft.answer||busy} onClick={()=>setEditing(v=>!v)}>✎ {editing?"完成修改":"自行修改"}</button></div></section></>}</>}
 {view==="question"&&<><section className="quickReplyQuestions"><h3>先點選要回答的問題</h3><div>{data.questions.map((q,i)=>{const done=drafts[String(q.slotIndex)]?.completed===true;return <button key={q.slotIndex} className={i===activeQuestion?"selected":""} onClick={()=>pickTarget("question",i)}><span>{done?"✓":`Q${q.questionNumber}`}</span><b><em>{q.itemTitle}</em>{q.question}</b><small>{done?"已完成回答":i===activeQuestion?"目前選取":"點此回答"}</small></button>})}</div></section>{question&&<>{!question.manualOnly&&<section className="quickReplyCategoryPicker"><h3>Q{question.questionNumber} 要判斷哪一類？</h3><p><b>{question.itemTitle}</b>{question.question}</p><div>{data.topics.map(t=><button key={t.code} className={`${categoryCode===t.code?"active":""} ${draft.selections[t.code]?"answered":""}`} onClick={()=>setActiveCategory(c=>({...c,[questionKey]:t.code}))}><span>{t.icon}</span>{t.title}{recommended.has(t.code)&&<small>預設</small>}</button>)}</div></section>}{!question.manualOnly&&category&&<section className="quickReplyOptions"><h3>{category.icon} {category.title}</h3><div>{category.options.map(o=><button key={o.code} className={draft.selections[category.code]===o.code?"selected":""} onClick={()=>choose(o.code)} disabled={busy}>{draft.selections[category.code]===o.code&&<span>✓</span>}{o.label}</button>)}</div>{draft.selections[category.code]&&<button className="quickReplyRemoveCategory" onClick={removeCategory}>移除這一類判斷</button>}</section>}<section className="quickReplyPreview"><div><h3>Q{question.questionNumber} 回覆預覽</h3></div>{editing||question.manualOnly?<textarea value={draft.answer} onChange={e=>{const answer=e.target.value;setDrafts(c=>({...c,[questionKey]:{...draft,answer,completed:!!answer.trim()}}))}} autoFocus/>:<p>{draft.answer||"請先選擇分類，再點選判斷結果。"}</p>}<div className="quickReplyPreviewActions">{!question.manualOnly&&<button disabled={!draft.answer||busy} onClick={()=>void compose(draft.selections,true)}>↻ 換一種說法</button>}<button disabled={!draft.answer||busy} onClick={()=>setEditing(v=>!v)}>✎ {editing?"完成修改":"自行修改"}</button></div></section></>}</>}
 {error&&<div className="quickReplyError">{error}</div>}{written&&<div className="quickReplySuccess">✅ 已成功寫入 Google 諮詢單</div>}<footer><button className="quickReplyWrite" disabled={!hasAnswer||busy} onClick={()=>void write()}>{busy?"處理中…":written?"再次寫入更新":"確認寫入全部回答"}</button>{written&&<a href={data.documentUrl} target="_blank" rel="noreferrer">查看 Google 文件</a>}<button className="quickReplyCancel" onClick={onClose}>返回預約後台</button></footer></div>}</section></div>
}
